
const translations = {
  "en": {
    "nav_about": "About Us",
    "nav_services": "Services",
    "nav_projects": "Projects",
    "nav_clients": "Clients",
    "nav_contact": "Contact Us",
    "btn_enquiry": "Send Enquiry",
    "hero_eyebrow": "Engineering Comfort. Building Excellence.",
    "hero_title": "Integrated Engineering Solutions You Can Trust",
    "hero_text": "Delivering high-quality HVAC, Civil, MEP and Interior Decoration solutions with safety, integrity and unmatched performance.",
    "btn_services": "Our Services",
    "btn_projects": "Explore Projects",
    "pill_hvac": "HVAC Solutions",
    "pill_civil": "Civil Works",
    "pill_mep": "MEP Services",
    "pill_interior": "Interior Decoration",
    "hero_card_title": "Doha-based engineering partner",
    "hero_card_text": "Built for residential, commercial and industrial project delivery.",
    "project_hvac_label": "HVAC Projects",
    "project_hvac_title": "Central Chilled Water Plant",
    "project_hvac_text": "AHU/FAHU, ducting works, VRF/VRV systems, testing and balancing.",
    "project_civil_label": "Civil Projects",
    "project_civil_title": "Structural & Concrete Works",
    "project_civil_text": "Concrete, block work, masonry, waterproofing and external finishes.",
    "project_mep_label": "MEP Projects",
    "project_mep_title": "Electrical & Plumbing Systems",
    "project_mep_text": "Power distribution, lighting, drainage systems, BMS and control systems.",
    "project_interior_label": "Decoration Projects",
    "project_interior_title": "Fit-Out & Finishing Works",
    "project_interior_text": "Gypsum ceiling, painting, wall tiling, flooring, joinery and carpentry.",
    "about_eyebrow": "About Doha Call Line (DCL)",
    "about_title": "Engineering solutions that build better futures.",
    "about_text_1": "Doha Call Line is a Qatar-based multidisciplinary company providing HVAC Solutions, Civil Works, MEP Services and Interior Decoration for residential, commercial and industrial projects.",
    "about_text_2": "With over a decade of experience, DCL has grown from a trusted cooling solutions provider to a reliable engineering and construction partner known for quality, safety and timely delivery.",
    "stat_years": "Years Experience",
    "stat_projects": "Projects Completed",
    "stat_team": "Skilled Professionals",
    "vision_title": "Vision",
    "vision_text": "To become a leading engineering and construction service provider in Qatar, recognized for quality, innovation, reliability and sustainable solutions.",
    "mission_title": "Mission",
    "mission_text": "To deliver high-quality HVAC, Civil, MEP and Interior Decoration solutions through expertise, integrity and commitment to exceeding client expectations.",
    "values_eyebrow": "Core Values",
    "values_title": "Built on quality, safety and integrity.",
    "value_quality": "Quality",
    "value_quality_text": "We deliver quality workmanship in everything we do.",
    "value_safety": "Safety",
    "value_safety_text": "We prioritize safety for our people, clients and projects.",
    "value_integrity": "Integrity",
    "value_integrity_text": "We operate with honesty, transparency and fairness.",
    "value_innovation": "Innovation",
    "value_innovation_text": "We embrace new ideas and technology to deliver better solutions.",
    "value_sustainability": "Sustainability",
    "value_sustainability_text": "We are committed to environmental responsibility and a sustainable future.",
    "value_teamwork": "Teamwork",
    "value_teamwork_text": "We believe in collaboration to achieve excellence together.",
    "services_eyebrow": "Our Services",
    "services_title": "Complete engineering services under one platform.",
    "services_text": "We provide design, execution, testing and maintenance across four core service divisions.",
    "svc_hvac_title": "HVAC Solutions",
    "svc_hvac_text": "Design, supply, installation, testing and maintenance of air conditioning, ventilation and refrigeration systems.",
    "svc_civil_title": "Civil Works",
    "svc_civil_text": "High-quality civil construction with focus on strength, durability, safety and timely completion.",
    "svc_mep_title": "MEP Services",
    "svc_mep_text": "Integrated mechanical, electrical and plumbing solutions for efficient, safe and reliable building performance.",
    "svc_interior_title": "Interior Decoration",
    "svc_interior_text": "Functional and aesthetic interior fit-out works tailored to client requirements.",
    "solutions_eyebrow": "Integrated Engineering Solutions",
    "solutions_title": "We build more than projects — we build trust.",
    "sol_design": "Design & Engineering",
    "sol_design_text": "Technical drawings, calculations and engineering documentation.",
    "sol_procurement": "Procurement & Supply",
    "sol_procurement_text": "Material sourcing, supplier coordination and project logistics.",
    "sol_construction": "Construction & Installation",
    "sol_construction_text": "Site execution by skilled teams with quality and safety control.",
    "sol_testing": "Testing & Commissioning",
    "sol_testing_text": "Performance verification, inspection and handover readiness.",
    "sol_maintenance": "Operation & Maintenance",
    "sol_maintenance_text": "Reliable after-service support and preventive maintenance.",
    "sol_turnkey": "Turnkey Project Delivery",
    "sol_turnkey_text": "One platform from concept to completion.",
    "iso_quality": "Quality Management",
    "iso_env": "Environmental Management",
    "iso_safety": "Occupational Health & Safety",
    "team_eyebrow": "Team & Organization",
    "team_title": "Organized for efficient project delivery.",
    "team_text": "Our organizational structure is designed to ensure efficient project delivery, clear communication and accountability at every level.",
    "org_general": "General Manager",
    "org_engineers": "Engineers",
    "org_engineers_text": "Technical design, calculations, project planning and documentation.",
    "org_pm": "Project Managers",
    "org_pm_text": "Planning, budget, scheduling, client coordination and risk management.",
    "org_supervisors": "Supervisors",
    "org_supervisors_text": "Site supervision, quality monitoring and safe execution of works.",
    "org_technicians": "Technicians",
    "org_technicians_text": "Installation, testing, commissioning, operation and maintenance.",
    "org_support": "Support Functions",
    "org_support_text": "Admin, HR, procurement, QA/QC, finance and HSE support.",
    "hse_badge": "Safety First",
    "hse_title": "Health, Safety & Quality",
    "hse_text": "We are committed to the health, safety and well-being of our people, our clients and the communities in which we work.",
    "hse_ppe": "PPE Compliance",
    "hse_ppe_text": "Mandatory PPE, helmets, safety shoes, gloves and goggles.",
    "hse_risk": "Risk Assessment",
    "hse_risk_text": "Hazard identification, risk evaluation and control measures.",
    "hse_toolbox": "Toolbox Talks",
    "hse_toolbox_text": "Daily safety briefing, task planning and worker awareness.",
    "hse_emergency": "Emergency Response",
    "hse_emergency_text": "Emergency procedures, evacuation plans and first aid readiness.",
    "hse_quality": "Quality Inspections",
    "hse_quality_text": "Material inspections, method statements and final testing.",
    "hse_record": "Record & Reporting",
    "hse_record_text": "Inspection records, NCR tracking and corrective actions.",
    "why_eyebrow": "Why Choose Us",
    "why_title": "Reliable delivery from planning to commissioning.",
    "why_exp": "10+ Years Experience",
    "why_exp_text": "Extensive experience across HVAC, Civil, MEP and fit-out projects.",
    "why_manpower": "Skilled Technical Manpower",
    "why_manpower_text": "Qualified engineers, supervisors, technicians and skilled workers.",
    "why_qaqc": "Quality Assurance & QA/QC",
    "why_qaqc_text": "Strict compliance with specifications, inspection and standards.",
    "why_time": "On-Time Project Delivery",
    "why_time_text": "Efficient planning, coordination and execution without compromising quality.",
    "why_hse": "HSE & Safety Commitment",
    "why_hse_text": "Risk assessment, toolbox talks and safe working procedures.",
    "why_integrated": "Integrated Engineering Solutions",
    "why_integrated_text": "HVAC, Civil, MEP and Interior services under one coordinated platform.",
    "projects_eyebrow": "Our Projects",
    "projects_title": "Delivering excellence across every project.",
    "port_hvac": "HVAC Installation",
    "port_civil": "Civil Construction",
    "port_mep": "MEP Systems",
    "port_interior": "Interior Fit-Out",
    "clients_eyebrow": "Major Clients",
    "clients_title": "Trusted by leading organizations across Qatar.",
    "client_qatar": "Delivered comprehensive MEP solutions for various museum facilities, ensuring world-class comfort, efficiency, and reliability.",
    "client_redco": "Executed HVAC, plumbing, and MEP works for multiple residential, commercial, and infrastructure projects with high quality and on-time delivery.",
    "client_secc": "Partnered on large-scale infrastructure and building projects, providing complete MEP and civil engineering solutions.",
    "client_aljaber": "Delivered a wide range of MEP services across critical and commercial projects, meeting the highest standards of safety, quality, and performance.",
    "contact_eyebrow": "Contact Us",
    "contact_title": "Let’s build the future together.",
    "contact_text": "Have a project in mind? Get in touch with us and we will deliver the right engineering solution.",
    "address_label": "Address",
    "phone_label": "Mobile",
    "email_label": "Emails",
    "footer_tagline": "Engineering Comfort. Building Excellence.",
    "modal_eyebrow": "Quick Contact",
    "modal_title": "Send Enquiry",
    "form_name": "Your Name",
    "form_contact": "Email / Phone",
    "form_message": "Message",
    "form_send": "Send Email"
  },
  "zh": {
    "nav_about": "关于我们",
    "nav_services": "服务",
    "nav_projects": "项目",
    "nav_clients": "客户",
    "nav_contact": "联系我们",
    "btn_enquiry": "发送询盘",
    "hero_eyebrow": "工程舒适，筑造卓越。",
    "hero_title": "值得信赖的一体化工程解决方案",
    "hero_text": "以安全、诚信和卓越表现提供高质量HVAC、土建、MEP和室内装饰解决方案。",
    "btn_services": "我们的服务",
    "btn_projects": "查看项目",
    "pill_hvac": "暖通空调解决方案",
    "pill_civil": "土建工程",
    "pill_mep": "机电服务",
    "pill_interior": "室内装饰",
    "hero_card_title": "多哈工程合作伙伴",
    "hero_card_text": "服务住宅、商业和工业项目交付。",
    "project_hvac_label": "HVAC Projects",
    "project_hvac_title": "Central Chilled Water Plant",
    "project_hvac_text": "AHU/FAHU, ducting works, VRF/VRV systems, testing and balancing.",
    "project_civil_label": "Civil Projects",
    "project_civil_title": "Structural & Concrete Works",
    "project_civil_text": "Concrete, block work, masonry, waterproofing and external finishes.",
    "project_mep_label": "MEP Projects",
    "project_mep_title": "Electrical & Plumbing Systems",
    "project_mep_text": "Power distribution, lighting, drainage systems, BMS and control systems.",
    "project_interior_label": "Decoration Projects",
    "project_interior_title": "Fit-Out & Finishing Works",
    "project_interior_text": "Gypsum ceiling, painting, wall tiling, flooring, joinery and carpentry.",
    "about_eyebrow": "关于 DOHA CALL LINE (DCL)",
    "about_title": "建设更美好未来的工程解决方案。",
    "about_text_1": "Doha Call Line 是一家位于卡塔尔的多专业公司，为住宅、商业和工业项目提供 HVAC、土建、MEP 和室内装饰服务。",
    "about_text_2": "凭借十多年的经验，DCL 已发展成为以质量、安全和准时交付著称的工程与建设伙伴。",
    "stat_years": "年经验",
    "stat_projects": "完成项目",
    "stat_team": "专业人员",
    "vision_title": "愿景",
    "vision_text": "成为卡塔尔领先的工程和建设服务提供商，以质量、创新、可靠性和可持续解决方案著称。",
    "mission_title": "使命",
    "mission_text": "通过专业、诚信和超越客户期望的承诺，提供高质量的 HVAC、土建、MEP 和室内装饰解决方案。",
    "values_eyebrow": "核心价值",
    "values_title": "以质量、安全和诚信为基础。",
    "value_quality": "质量",
    "value_quality_text": "我们在每项工作中都交付高质量工艺。",
    "value_safety": "安全",
    "value_safety_text": "我们重视员工、客户和项目的安全。",
    "value_integrity": "诚信",
    "value_integrity_text": "我们以诚实、透明和公平开展业务。",
    "value_innovation": "创新",
    "value_innovation_text": "我们采用新理念和技术提供更好的解决方案。",
    "value_sustainability": "可持续",
    "value_sustainability_text": "我们致力于环保责任和可持续未来。",
    "value_teamwork": "团队合作",
    "value_teamwork_text": "我们相信协作成就卓越。",
    "services_eyebrow": "我们的服务",
    "services_title": "一个平台提供完整工程服务。",
    "services_text": "我们在四个核心领域提供设计、执行、测试和维护。",
    "svc_hvac_title": "暖通空调解决方案",
    "svc_hvac_text": "Design, supply, installation, testing and maintenance of air conditioning, ventilation and refrigeration systems.",
    "svc_civil_title": "土建工程",
    "svc_civil_text": "High-quality civil construction with focus on strength, durability, safety and timely completion.",
    "svc_mep_title": "机电服务",
    "svc_mep_text": "Integrated mechanical, electrical and plumbing solutions for efficient, safe and reliable building performance.",
    "svc_interior_title": "室内装饰",
    "svc_interior_text": "Functional and aesthetic interior fit-out works tailored to client requirements.",
    "solutions_eyebrow": "一体化工程解决方案",
    "solutions_title": "我们不只建设项目，也建立信任。",
    "sol_design": "Design & Engineering",
    "sol_design_text": "Technical drawings, calculations and engineering documentation.",
    "sol_procurement": "Procurement & Supply",
    "sol_procurement_text": "Material sourcing, supplier coordination and project logistics.",
    "sol_construction": "Construction & Installation",
    "sol_construction_text": "Site execution by skilled teams with quality and safety control.",
    "sol_testing": "Testing & Commissioning",
    "sol_testing_text": "Performance verification, inspection and handover readiness.",
    "sol_maintenance": "Operation & Maintenance",
    "sol_maintenance_text": "Reliable after-service support and preventive maintenance.",
    "sol_turnkey": "Turnkey Project Delivery",
    "sol_turnkey_text": "One platform from concept to completion.",
    "iso_quality": "Quality Management",
    "iso_env": "Environmental Management",
    "iso_safety": "Occupational Health & Safety",
    "team_eyebrow": "团队与组织",
    "team_title": "为高效项目交付而组织。",
    "team_text": "我们的组织结构确保高效交付、清晰沟通和责任落实。",
    "org_general": "General Manager",
    "org_engineers": "Engineers",
    "org_engineers_text": "Technical design, calculations, project planning and documentation.",
    "org_pm": "Project Managers",
    "org_pm_text": "Planning, budget, scheduling, client coordination and risk management.",
    "org_supervisors": "Supervisors",
    "org_supervisors_text": "Site supervision, quality monitoring and safe execution of works.",
    "org_technicians": "Technicians",
    "org_technicians_text": "Installation, testing, commissioning, operation and maintenance.",
    "org_support": "Support Functions",
    "org_support_text": "Admin, HR, procurement, QA/QC, finance and HSE support.",
    "hse_badge": "Safety First",
    "hse_title": "健康、安全与质量",
    "hse_text": "我们致力于员工、客户及社区的健康、安全和福祉。",
    "hse_ppe": "PPE Compliance",
    "hse_ppe_text": "Mandatory PPE, helmets, safety shoes, gloves and goggles.",
    "hse_risk": "Risk Assessment",
    "hse_risk_text": "Hazard identification, risk evaluation and control measures.",
    "hse_toolbox": "Toolbox Talks",
    "hse_toolbox_text": "Daily safety briefing, task planning and worker awareness.",
    "hse_emergency": "Emergency Response",
    "hse_emergency_text": "Emergency procedures, evacuation plans and first aid readiness.",
    "hse_quality": "Quality Inspections",
    "hse_quality_text": "Material inspections, method statements and final testing.",
    "hse_record": "Record & Reporting",
    "hse_record_text": "Inspection records, NCR tracking and corrective actions.",
    "why_eyebrow": "为什么选择我们",
    "why_title": "从规划到调试的可靠交付。",
    "why_exp": "10+ Years Experience",
    "why_exp_text": "Extensive experience across HVAC, Civil, MEP and fit-out projects.",
    "why_manpower": "Skilled Technical Manpower",
    "why_manpower_text": "Qualified engineers, supervisors, technicians and skilled workers.",
    "why_qaqc": "Quality Assurance & QA/QC",
    "why_qaqc_text": "Strict compliance with specifications, inspection and standards.",
    "why_time": "On-Time Project Delivery",
    "why_time_text": "Efficient planning, coordination and execution without compromising quality.",
    "why_hse": "HSE & Safety Commitment",
    "why_hse_text": "Risk assessment, toolbox talks and safe working procedures.",
    "why_integrated": "Integrated Engineering Solutions",
    "why_integrated_text": "HVAC, Civil, MEP and Interior services under one coordinated platform.",
    "projects_eyebrow": "我们的项目",
    "projects_title": "在每个项目中交付卓越。",
    "port_hvac": "HVAC Installation",
    "port_civil": "Civil Construction",
    "port_mep": "MEP Systems",
    "port_interior": "Interior Fit-Out",
    "clients_eyebrow": "主要客户",
    "clients_title": "受到卡塔尔领先机构的信赖。",
    "client_qatar": "Delivered comprehensive MEP solutions for various museum facilities, ensuring world-class comfort, efficiency, and reliability.",
    "client_redco": "Executed HVAC, plumbing, and MEP works for multiple residential, commercial, and infrastructure projects with high quality and on-time delivery.",
    "client_secc": "Partnered on large-scale infrastructure and building projects, providing complete MEP and civil engineering solutions.",
    "client_aljaber": "Delivered a wide range of MEP services across critical and commercial projects, meeting the highest standards of safety, quality, and performance.",
    "contact_eyebrow": "联系我们",
    "contact_title": "让我们一起建设未来。",
    "contact_text": "如果您有项目需求，请联系我们，我们将提供合适的工程解决方案。",
    "address_label": "Address",
    "phone_label": "Mobile",
    "email_label": "Emails",
    "footer_tagline": "工程舒适，筑造卓越。",
    "modal_eyebrow": "Quick Contact",
    "modal_title": "发送询盘",
    "form_name": "Your Name",
    "form_contact": "Email / Phone",
    "form_message": "Message",
    "form_send": "Send Email"
  },
  "fr": {
    "nav_about": "À propos",
    "nav_services": "Services",
    "nav_projects": "Projets",
    "nav_clients": "Clients",
    "nav_contact": "Contact",
    "btn_enquiry": "Envoyer une demande",
    "hero_eyebrow": "Confort d’ingénierie. Excellence de construction.",
    "hero_title": "Solutions d’ingénierie intégrées de confiance",
    "hero_text": "Nous fournissons des solutions HVAC, génie civil, MEP et décoration intérieure avec sécurité, intégrité et performance.",
    "btn_services": "Nos services",
    "btn_projects": "Voir les projets",
    "pill_hvac": "Solutions HVAC",
    "pill_civil": "Travaux civils",
    "pill_mep": "Services MEP",
    "pill_interior": "Décoration intérieure",
    "hero_card_title": "Partenaire d’ingénierie basé à Doha",
    "hero_card_text": "Conçu pour les projets résidentiels, commerciaux et industriels.",
    "project_hvac_label": "HVAC Projects",
    "project_hvac_title": "Central Chilled Water Plant",
    "project_hvac_text": "AHU/FAHU, ducting works, VRF/VRV systems, testing and balancing.",
    "project_civil_label": "Civil Projects",
    "project_civil_title": "Structural & Concrete Works",
    "project_civil_text": "Concrete, block work, masonry, waterproofing and external finishes.",
    "project_mep_label": "MEP Projects",
    "project_mep_title": "Electrical & Plumbing Systems",
    "project_mep_text": "Power distribution, lighting, drainage systems, BMS and control systems.",
    "project_interior_label": "Decoration Projects",
    "project_interior_title": "Fit-Out & Finishing Works",
    "project_interior_text": "Gypsum ceiling, painting, wall tiling, flooring, joinery and carpentry.",
    "about_eyebrow": "À propos de Doha Call Line (DCL)",
    "about_title": "Des solutions d’ingénierie pour construire un avenir meilleur.",
    "about_text_1": "Doha Call Line est une entreprise multidisciplinaire basée au Qatar fournissant des solutions HVAC, travaux civils, MEP et décoration intérieure.",
    "about_text_2": "Avec plus d’une décennie d’expérience, DCL est devenue un partenaire reconnu pour la qualité, la sécurité et le respect des délais.",
    "stat_years": "Années d’expérience",
    "stat_projects": "Projets réalisés",
    "stat_team": "Professionnels qualifiés",
    "vision_title": "Vision",
    "vision_text": "Devenir un fournisseur leader de services d’ingénierie et de construction au Qatar, reconnu pour la qualité, l’innovation et la durabilité.",
    "mission_title": "Mission",
    "mission_text": "Fournir des solutions HVAC, Civiles, MEP et décoration intérieure de haute qualité avec expertise, intégrité et engagement.",
    "values_eyebrow": "Valeurs clés",
    "values_title": "Fondé sur la qualité, la sécurité et l’intégrité.",
    "value_quality": "Qualité",
    "value_quality_text": "Nous livrons un travail de qualité dans tout ce que nous faisons.",
    "value_safety": "Sécurité",
    "value_safety_text": "Nous privilégions la sécurité de nos équipes, clients et projets.",
    "value_integrity": "Intégrité",
    "value_integrity_text": "Nous travaillons avec honnêteté, transparence et équité.",
    "value_innovation": "Innovation",
    "value_innovation_text": "Nous adoptons les nouvelles idées et technologies.",
    "value_sustainability": "Durabilité",
    "value_sustainability_text": "Nous sommes engagés envers la responsabilité environnementale.",
    "value_teamwork": "Travail d’équipe",
    "value_teamwork_text": "Nous croyons à la collaboration pour atteindre l’excellence.",
    "services_eyebrow": "Nos services",
    "services_title": "Des services d’ingénierie complets sur une seule plateforme.",
    "services_text": "Nous assurons conception, exécution, tests et maintenance dans quatre divisions.",
    "svc_hvac_title": "Solutions HVAC",
    "svc_hvac_text": "Design, supply, installation, testing and maintenance of air conditioning, ventilation and refrigeration systems.",
    "svc_civil_title": "Travaux civils",
    "svc_civil_text": "High-quality civil construction with focus on strength, durability, safety and timely completion.",
    "svc_mep_title": "Services MEP",
    "svc_mep_text": "Integrated mechanical, electrical and plumbing solutions for efficient, safe and reliable building performance.",
    "svc_interior_title": "Décoration intérieure",
    "svc_interior_text": "Functional and aesthetic interior fit-out works tailored to client requirements.",
    "solutions_eyebrow": "Solutions d’ingénierie intégrées",
    "solutions_title": "Nous construisons plus que des projets — nous construisons la confiance.",
    "sol_design": "Design & Engineering",
    "sol_design_text": "Technical drawings, calculations and engineering documentation.",
    "sol_procurement": "Procurement & Supply",
    "sol_procurement_text": "Material sourcing, supplier coordination and project logistics.",
    "sol_construction": "Construction & Installation",
    "sol_construction_text": "Site execution by skilled teams with quality and safety control.",
    "sol_testing": "Testing & Commissioning",
    "sol_testing_text": "Performance verification, inspection and handover readiness.",
    "sol_maintenance": "Operation & Maintenance",
    "sol_maintenance_text": "Reliable after-service support and preventive maintenance.",
    "sol_turnkey": "Turnkey Project Delivery",
    "sol_turnkey_text": "One platform from concept to completion.",
    "iso_quality": "Quality Management",
    "iso_env": "Environmental Management",
    "iso_safety": "Occupational Health & Safety",
    "team_eyebrow": "Équipe & Organisation",
    "team_title": "Organisés pour une livraison efficace des projets.",
    "team_text": "Notre structure garantit une livraison efficace, une communication claire et la responsabilité.",
    "org_general": "General Manager",
    "org_engineers": "Engineers",
    "org_engineers_text": "Technical design, calculations, project planning and documentation.",
    "org_pm": "Project Managers",
    "org_pm_text": "Planning, budget, scheduling, client coordination and risk management.",
    "org_supervisors": "Supervisors",
    "org_supervisors_text": "Site supervision, quality monitoring and safe execution of works.",
    "org_technicians": "Technicians",
    "org_technicians_text": "Installation, testing, commissioning, operation and maintenance.",
    "org_support": "Support Functions",
    "org_support_text": "Admin, HR, procurement, QA/QC, finance and HSE support.",
    "hse_badge": "Safety First",
    "hse_title": "Santé, sécurité & qualité",
    "hse_text": "Nous nous engageons pour la santé, la sécurité et le bien-être de nos équipes, clients et communautés.",
    "hse_ppe": "PPE Compliance",
    "hse_ppe_text": "Mandatory PPE, helmets, safety shoes, gloves and goggles.",
    "hse_risk": "Risk Assessment",
    "hse_risk_text": "Hazard identification, risk evaluation and control measures.",
    "hse_toolbox": "Toolbox Talks",
    "hse_toolbox_text": "Daily safety briefing, task planning and worker awareness.",
    "hse_emergency": "Emergency Response",
    "hse_emergency_text": "Emergency procedures, evacuation plans and first aid readiness.",
    "hse_quality": "Quality Inspections",
    "hse_quality_text": "Material inspections, method statements and final testing.",
    "hse_record": "Record & Reporting",
    "hse_record_text": "Inspection records, NCR tracking and corrective actions.",
    "why_eyebrow": "Pourquoi nous choisir",
    "why_title": "Une livraison fiable de la planification à la mise en service.",
    "why_exp": "10+ Years Experience",
    "why_exp_text": "Extensive experience across HVAC, Civil, MEP and fit-out projects.",
    "why_manpower": "Skilled Technical Manpower",
    "why_manpower_text": "Qualified engineers, supervisors, technicians and skilled workers.",
    "why_qaqc": "Quality Assurance & QA/QC",
    "why_qaqc_text": "Strict compliance with specifications, inspection and standards.",
    "why_time": "On-Time Project Delivery",
    "why_time_text": "Efficient planning, coordination and execution without compromising quality.",
    "why_hse": "HSE & Safety Commitment",
    "why_hse_text": "Risk assessment, toolbox talks and safe working procedures.",
    "why_integrated": "Integrated Engineering Solutions",
    "why_integrated_text": "HVAC, Civil, MEP and Interior services under one coordinated platform.",
    "projects_eyebrow": "Nos projets",
    "projects_title": "L’excellence dans chaque projet.",
    "port_hvac": "HVAC Installation",
    "port_civil": "Civil Construction",
    "port_mep": "MEP Systems",
    "port_interior": "Interior Fit-Out",
    "clients_eyebrow": "Principaux clients",
    "clients_title": "Reconnu par les grandes organisations au Qatar.",
    "client_qatar": "Delivered comprehensive MEP solutions for various museum facilities, ensuring world-class comfort, efficiency, and reliability.",
    "client_redco": "Executed HVAC, plumbing, and MEP works for multiple residential, commercial, and infrastructure projects with high quality and on-time delivery.",
    "client_secc": "Partnered on large-scale infrastructure and building projects, providing complete MEP and civil engineering solutions.",
    "client_aljaber": "Delivered a wide range of MEP services across critical and commercial projects, meeting the highest standards of safety, quality, and performance.",
    "contact_eyebrow": "Contact",
    "contact_title": "Construisons l’avenir ensemble.",
    "contact_text": "Vous avez un projet? Contactez-nous et nous fournirons la solution d’ingénierie adaptée.",
    "address_label": "Address",
    "phone_label": "Mobile",
    "email_label": "Emails",
    "footer_tagline": "Confort d’ingénierie. Excellence de construction.",
    "modal_eyebrow": "Quick Contact",
    "modal_title": "Envoyer une demande",
    "form_name": "Your Name",
    "form_contact": "Email / Phone",
    "form_message": "Message",
    "form_send": "Send Email"
  },
  "es": {
    "nav_about": "Sobre nosotros",
    "nav_services": "Servicios",
    "nav_projects": "Proyectos",
    "nav_clients": "Clientes",
    "nav_contact": "Contacto",
    "btn_enquiry": "Enviar consulta",
    "hero_eyebrow": "Confort de ingeniería. Excelencia en construcción.",
    "hero_title": "Soluciones integradas de ingeniería confiables",
    "hero_text": "Ofrecemos soluciones HVAC, civiles, MEP y de decoración interior con seguridad, integridad y alto rendimiento.",
    "btn_services": "Nuestros servicios",
    "btn_projects": "Ver proyectos",
    "pill_hvac": "Soluciones HVAC",
    "pill_civil": "Obras civiles",
    "pill_mep": "Servicios MEP",
    "pill_interior": "Decoración interior",
    "hero_card_title": "Socio de ingeniería en Doha",
    "hero_card_text": "Para proyectos residenciales, comerciales e industriales.",
    "project_hvac_label": "HVAC Projects",
    "project_hvac_title": "Central Chilled Water Plant",
    "project_hvac_text": "AHU/FAHU, ducting works, VRF/VRV systems, testing and balancing.",
    "project_civil_label": "Civil Projects",
    "project_civil_title": "Structural & Concrete Works",
    "project_civil_text": "Concrete, block work, masonry, waterproofing and external finishes.",
    "project_mep_label": "MEP Projects",
    "project_mep_title": "Electrical & Plumbing Systems",
    "project_mep_text": "Power distribution, lighting, drainage systems, BMS and control systems.",
    "project_interior_label": "Decoration Projects",
    "project_interior_title": "Fit-Out & Finishing Works",
    "project_interior_text": "Gypsum ceiling, painting, wall tiling, flooring, joinery and carpentry.",
    "about_eyebrow": "Sobre Doha Call Line (DCL)",
    "about_title": "Soluciones de ingeniería que construyen mejores futuros.",
    "about_text_1": "Doha Call Line es una empresa multidisciplinaria en Qatar que ofrece soluciones HVAC, obras civiles, MEP y decoración interior.",
    "about_text_2": "Con más de una década de experiencia, DCL es un socio reconocido por calidad, seguridad y entrega puntual.",
    "stat_years": "Años de experiencia",
    "stat_projects": "Proyectos completados",
    "stat_team": "Profesionales calificados",
    "vision_title": "Visión",
    "vision_text": "Ser un proveedor líder de ingeniería y construcción en Qatar, reconocido por calidad, innovación, confiabilidad y sostenibilidad.",
    "mission_title": "Misión",
    "mission_text": "Entregar soluciones HVAC, civiles, MEP y decoración interior de alta calidad con experiencia, integridad y compromiso.",
    "values_eyebrow": "Valores centrales",
    "values_title": "Construido sobre calidad, seguridad e integridad.",
    "value_quality": "Calidad",
    "value_quality_text": "Entregamos calidad en todo lo que hacemos.",
    "value_safety": "Seguridad",
    "value_safety_text": "Priorizamos la seguridad de nuestra gente, clientes y proyectos.",
    "value_integrity": "Integridad",
    "value_integrity_text": "Operamos con honestidad, transparencia y justicia.",
    "value_innovation": "Innovación",
    "value_innovation_text": "Adoptamos nuevas ideas y tecnología para mejores soluciones.",
    "value_sustainability": "Sostenibilidad",
    "value_sustainability_text": "Estamos comprometidos con la responsabilidad ambiental.",
    "value_teamwork": "Trabajo en equipo",
    "value_teamwork_text": "Creemos en la colaboración para alcanzar la excelencia.",
    "services_eyebrow": "Nuestros servicios",
    "services_title": "Servicios de ingeniería completos en una sola plataforma.",
    "services_text": "Ofrecemos diseño, ejecución, pruebas y mantenimiento en cuatro divisiones.",
    "svc_hvac_title": "Soluciones HVAC",
    "svc_hvac_text": "Design, supply, installation, testing and maintenance of air conditioning, ventilation and refrigeration systems.",
    "svc_civil_title": "Obras civiles",
    "svc_civil_text": "High-quality civil construction with focus on strength, durability, safety and timely completion.",
    "svc_mep_title": "Servicios MEP",
    "svc_mep_text": "Integrated mechanical, electrical and plumbing solutions for efficient, safe and reliable building performance.",
    "svc_interior_title": "Decoración interior",
    "svc_interior_text": "Functional and aesthetic interior fit-out works tailored to client requirements.",
    "solutions_eyebrow": "Soluciones integradas de ingeniería",
    "solutions_title": "Construimos más que proyectos: construimos confianza.",
    "sol_design": "Design & Engineering",
    "sol_design_text": "Technical drawings, calculations and engineering documentation.",
    "sol_procurement": "Procurement & Supply",
    "sol_procurement_text": "Material sourcing, supplier coordination and project logistics.",
    "sol_construction": "Construction & Installation",
    "sol_construction_text": "Site execution by skilled teams with quality and safety control.",
    "sol_testing": "Testing & Commissioning",
    "sol_testing_text": "Performance verification, inspection and handover readiness.",
    "sol_maintenance": "Operation & Maintenance",
    "sol_maintenance_text": "Reliable after-service support and preventive maintenance.",
    "sol_turnkey": "Turnkey Project Delivery",
    "sol_turnkey_text": "One platform from concept to completion.",
    "iso_quality": "Quality Management",
    "iso_env": "Environmental Management",
    "iso_safety": "Occupational Health & Safety",
    "team_eyebrow": "Equipo y organización",
    "team_title": "Organizados para una entrega eficiente.",
    "team_text": "Nuestra estructura asegura entrega eficiente, comunicación clara y responsabilidad.",
    "org_general": "General Manager",
    "org_engineers": "Engineers",
    "org_engineers_text": "Technical design, calculations, project planning and documentation.",
    "org_pm": "Project Managers",
    "org_pm_text": "Planning, budget, scheduling, client coordination and risk management.",
    "org_supervisors": "Supervisors",
    "org_supervisors_text": "Site supervision, quality monitoring and safe execution of works.",
    "org_technicians": "Technicians",
    "org_technicians_text": "Installation, testing, commissioning, operation and maintenance.",
    "org_support": "Support Functions",
    "org_support_text": "Admin, HR, procurement, QA/QC, finance and HSE support.",
    "hse_badge": "Safety First",
    "hse_title": "Salud, seguridad y calidad",
    "hse_text": "Nos comprometemos con la salud, seguridad y bienestar de nuestra gente, clientes y comunidades.",
    "hse_ppe": "PPE Compliance",
    "hse_ppe_text": "Mandatory PPE, helmets, safety shoes, gloves and goggles.",
    "hse_risk": "Risk Assessment",
    "hse_risk_text": "Hazard identification, risk evaluation and control measures.",
    "hse_toolbox": "Toolbox Talks",
    "hse_toolbox_text": "Daily safety briefing, task planning and worker awareness.",
    "hse_emergency": "Emergency Response",
    "hse_emergency_text": "Emergency procedures, evacuation plans and first aid readiness.",
    "hse_quality": "Quality Inspections",
    "hse_quality_text": "Material inspections, method statements and final testing.",
    "hse_record": "Record & Reporting",
    "hse_record_text": "Inspection records, NCR tracking and corrective actions.",
    "why_eyebrow": "Por qué elegirnos",
    "why_title": "Entrega confiable desde la planificación hasta la puesta en marcha.",
    "why_exp": "10+ Years Experience",
    "why_exp_text": "Extensive experience across HVAC, Civil, MEP and fit-out projects.",
    "why_manpower": "Skilled Technical Manpower",
    "why_manpower_text": "Qualified engineers, supervisors, technicians and skilled workers.",
    "why_qaqc": "Quality Assurance & QA/QC",
    "why_qaqc_text": "Strict compliance with specifications, inspection and standards.",
    "why_time": "On-Time Project Delivery",
    "why_time_text": "Efficient planning, coordination and execution without compromising quality.",
    "why_hse": "HSE & Safety Commitment",
    "why_hse_text": "Risk assessment, toolbox talks and safe working procedures.",
    "why_integrated": "Integrated Engineering Solutions",
    "why_integrated_text": "HVAC, Civil, MEP and Interior services under one coordinated platform.",
    "projects_eyebrow": "Nuestros proyectos",
    "projects_title": "Excelencia en cada proyecto.",
    "port_hvac": "HVAC Installation",
    "port_civil": "Civil Construction",
    "port_mep": "MEP Systems",
    "port_interior": "Interior Fit-Out",
    "clients_eyebrow": "Clientes principales",
    "clients_title": "Confiados por organizaciones líderes en Qatar.",
    "client_qatar": "Delivered comprehensive MEP solutions for various museum facilities, ensuring world-class comfort, efficiency, and reliability.",
    "client_redco": "Executed HVAC, plumbing, and MEP works for multiple residential, commercial, and infrastructure projects with high quality and on-time delivery.",
    "client_secc": "Partnered on large-scale infrastructure and building projects, providing complete MEP and civil engineering solutions.",
    "client_aljaber": "Delivered a wide range of MEP services across critical and commercial projects, meeting the highest standards of safety, quality, and performance.",
    "contact_eyebrow": "Contacto",
    "contact_title": "Construyamos el futuro juntos.",
    "contact_text": "¿Tienes un proyecto? Contáctanos y entregaremos la solución de ingeniería adecuada.",
    "address_label": "Address",
    "phone_label": "Mobile",
    "email_label": "Emails",
    "footer_tagline": "Confort de ingeniería. Excelencia en construcción.",
    "modal_eyebrow": "Quick Contact",
    "modal_title": "Enviar consulta",
    "form_name": "Your Name",
    "form_contact": "Email / Phone",
    "form_message": "Message",
    "form_send": "Send Email"
  },
  "ar": {
    "nav_about": "من نحن",
    "nav_services": "الخدمات",
    "nav_projects": "المشاريع",
    "nav_clients": "العملاء",
    "nav_contact": "اتصل بنا",
    "btn_enquiry": "إرسال استفسار",
    "hero_eyebrow": "راحة هندسية. تميز في البناء.",
    "hero_title": "حلول هندسية متكاملة يمكنك الوثوق بها",
    "hero_text": "نقدم حلول التكييف والأعمال المدنية والميكانيكية والكهربائية والسباكة والديكور الداخلي بجودة عالية وسلامة ونزاهة.",
    "btn_services": "خدماتنا",
    "btn_projects": "استعرض المشاريع",
    "pill_hvac": "حلول التكييف",
    "pill_civil": "الأعمال المدنية",
    "pill_mep": "خدمات MEP",
    "pill_interior": "الديكور الداخلي",
    "hero_card_title": "شريك هندسي في الدوحة",
    "hero_card_text": "للمشاريع السكنية والتجارية والصناعية.",
    "project_hvac_label": "HVAC Projects",
    "project_hvac_title": "Central Chilled Water Plant",
    "project_hvac_text": "AHU/FAHU, ducting works, VRF/VRV systems, testing and balancing.",
    "project_civil_label": "Civil Projects",
    "project_civil_title": "Structural & Concrete Works",
    "project_civil_text": "Concrete, block work, masonry, waterproofing and external finishes.",
    "project_mep_label": "MEP Projects",
    "project_mep_title": "Electrical & Plumbing Systems",
    "project_mep_text": "Power distribution, lighting, drainage systems, BMS and control systems.",
    "project_interior_label": "Decoration Projects",
    "project_interior_title": "Fit-Out & Finishing Works",
    "project_interior_text": "Gypsum ceiling, painting, wall tiling, flooring, joinery and carpentry.",
    "about_eyebrow": "عن دوحة كول لاين (DCL)",
    "about_title": "حلول هندسية تبني مستقبلاً أفضل.",
    "about_text_1": "دوحة كول لاين شركة متعددة التخصصات في قطر تقدم حلول التكييف والأعمال المدنية وMEP والديكور الداخلي للمشاريع السكنية والتجارية والصناعية.",
    "about_text_2": "بخبرة تتجاوز عشر سنوات، أصبحت DCL شريكاً موثوقاً في الهندسة والإنشاء معروفاً بالجودة والسلامة والتسليم في الوقت المحدد.",
    "stat_years": "سنوات خبرة",
    "stat_projects": "مشاريع منجزة",
    "stat_team": "محترفون مهرة",
    "vision_title": "الرؤية",
    "vision_text": "أن نصبح من أبرز مزودي خدمات الهندسة والإنشاء في قطر، معروفين بالجودة والابتكار والاعتمادية والحلول المستدامة.",
    "mission_title": "الرسالة",
    "mission_text": "تقديم حلول عالية الجودة في التكييف والأعمال المدنية وMEP والديكور الداخلي من خلال الخبرة والنزاهة والالتزام بتجاوز توقعات العملاء.",
    "values_eyebrow": "القيم الأساسية",
    "values_title": "نرتكز على الجودة والسلامة والنزاهة.",
    "value_quality": "الجودة",
    "value_quality_text": "نقدم جودة عالية في كل ما نقوم به.",
    "value_safety": "السلامة",
    "value_safety_text": "نضع سلامة أفرادنا وعملائنا ومشاريعنا في المقدمة.",
    "value_integrity": "النزاهة",
    "value_integrity_text": "نعمل بصدق وشفافية وعدالة.",
    "value_innovation": "الابتكار",
    "value_innovation_text": "نتبنى الأفكار والتقنيات الجديدة لتقديم حلول أفضل.",
    "value_sustainability": "الاستدامة",
    "value_sustainability_text": "نلتزم بالمسؤولية البيئية ومستقبل مستدام.",
    "value_teamwork": "العمل الجماعي",
    "value_teamwork_text": "نؤمن بالتعاون لتحقيق التميز.",
    "services_eyebrow": "خدماتنا",
    "services_title": "خدمات هندسية متكاملة في منصة واحدة.",
    "services_text": "نقدم التصميم والتنفيذ والاختبار والصيانة عبر أربعة أقسام رئيسية.",
    "svc_hvac_title": "حلول التكييف",
    "svc_hvac_text": "Design, supply, installation, testing and maintenance of air conditioning, ventilation and refrigeration systems.",
    "svc_civil_title": "الأعمال المدنية",
    "svc_civil_text": "High-quality civil construction with focus on strength, durability, safety and timely completion.",
    "svc_mep_title": "خدمات MEP",
    "svc_mep_text": "Integrated mechanical, electrical and plumbing solutions for efficient, safe and reliable building performance.",
    "svc_interior_title": "الديكور الداخلي",
    "svc_interior_text": "Functional and aesthetic interior fit-out works tailored to client requirements.",
    "solutions_eyebrow": "حلول هندسية متكاملة",
    "solutions_title": "نحن لا نبني المشاريع فقط، بل نبني الثقة.",
    "sol_design": "Design & Engineering",
    "sol_design_text": "Technical drawings, calculations and engineering documentation.",
    "sol_procurement": "Procurement & Supply",
    "sol_procurement_text": "Material sourcing, supplier coordination and project logistics.",
    "sol_construction": "Construction & Installation",
    "sol_construction_text": "Site execution by skilled teams with quality and safety control.",
    "sol_testing": "Testing & Commissioning",
    "sol_testing_text": "Performance verification, inspection and handover readiness.",
    "sol_maintenance": "Operation & Maintenance",
    "sol_maintenance_text": "Reliable after-service support and preventive maintenance.",
    "sol_turnkey": "Turnkey Project Delivery",
    "sol_turnkey_text": "One platform from concept to completion.",
    "iso_quality": "Quality Management",
    "iso_env": "Environmental Management",
    "iso_safety": "Occupational Health & Safety",
    "team_eyebrow": "الفريق والتنظيم",
    "team_title": "منظمون لتسليم المشاريع بكفاءة.",
    "team_text": "تم تصميم هيكلنا التنظيمي لضمان التسليم الفعال والتواصل الواضح والمسؤولية.",
    "org_general": "General Manager",
    "org_engineers": "Engineers",
    "org_engineers_text": "Technical design, calculations, project planning and documentation.",
    "org_pm": "Project Managers",
    "org_pm_text": "Planning, budget, scheduling, client coordination and risk management.",
    "org_supervisors": "Supervisors",
    "org_supervisors_text": "Site supervision, quality monitoring and safe execution of works.",
    "org_technicians": "Technicians",
    "org_technicians_text": "Installation, testing, commissioning, operation and maintenance.",
    "org_support": "Support Functions",
    "org_support_text": "Admin, HR, procurement, QA/QC, finance and HSE support.",
    "hse_badge": "Safety First",
    "hse_title": "الصحة والسلامة والجودة",
    "hse_text": "نلتزم بصحة وسلامة ورفاهية موظفينا وعملائنا والمجتمعات التي نعمل فيها.",
    "hse_ppe": "PPE Compliance",
    "hse_ppe_text": "Mandatory PPE, helmets, safety shoes, gloves and goggles.",
    "hse_risk": "Risk Assessment",
    "hse_risk_text": "Hazard identification, risk evaluation and control measures.",
    "hse_toolbox": "Toolbox Talks",
    "hse_toolbox_text": "Daily safety briefing, task planning and worker awareness.",
    "hse_emergency": "Emergency Response",
    "hse_emergency_text": "Emergency procedures, evacuation plans and first aid readiness.",
    "hse_quality": "Quality Inspections",
    "hse_quality_text": "Material inspections, method statements and final testing.",
    "hse_record": "Record & Reporting",
    "hse_record_text": "Inspection records, NCR tracking and corrective actions.",
    "why_eyebrow": "لماذا تختارنا",
    "why_title": "تسليم موثوق من التخطيط إلى التشغيل.",
    "why_exp": "10+ Years Experience",
    "why_exp_text": "Extensive experience across HVAC, Civil, MEP and fit-out projects.",
    "why_manpower": "Skilled Technical Manpower",
    "why_manpower_text": "Qualified engineers, supervisors, technicians and skilled workers.",
    "why_qaqc": "Quality Assurance & QA/QC",
    "why_qaqc_text": "Strict compliance with specifications, inspection and standards.",
    "why_time": "On-Time Project Delivery",
    "why_time_text": "Efficient planning, coordination and execution without compromising quality.",
    "why_hse": "HSE & Safety Commitment",
    "why_hse_text": "Risk assessment, toolbox talks and safe working procedures.",
    "why_integrated": "Integrated Engineering Solutions",
    "why_integrated_text": "HVAC, Civil, MEP and Interior services under one coordinated platform.",
    "projects_eyebrow": "مشاريعنا",
    "projects_title": "نقدم التميز في كل مشروع.",
    "port_hvac": "HVAC Installation",
    "port_civil": "Civil Construction",
    "port_mep": "MEP Systems",
    "port_interior": "Interior Fit-Out",
    "clients_eyebrow": "العملاء الرئيسيون",
    "clients_title": "موثوقون من قبل مؤسسات رائدة في قطر.",
    "client_qatar": "Delivered comprehensive MEP solutions for various museum facilities, ensuring world-class comfort, efficiency, and reliability.",
    "client_redco": "Executed HVAC, plumbing, and MEP works for multiple residential, commercial, and infrastructure projects with high quality and on-time delivery.",
    "client_secc": "Partnered on large-scale infrastructure and building projects, providing complete MEP and civil engineering solutions.",
    "client_aljaber": "Delivered a wide range of MEP services across critical and commercial projects, meeting the highest standards of safety, quality, and performance.",
    "contact_eyebrow": "اتصل بنا",
    "contact_title": "لنبني المستقبل معاً.",
    "contact_text": "هل لديك مشروع؟ تواصل معنا وسنقدم الحل الهندسي المناسب.",
    "address_label": "Address",
    "phone_label": "Mobile",
    "email_label": "Emails",
    "footer_tagline": "راحة هندسية. تميز في البناء.",
    "modal_eyebrow": "Quick Contact",
    "modal_title": "إرسال استفسار",
    "form_name": "Your Name",
    "form_contact": "Email / Phone",
    "form_message": "Message",
    "form_send": "Send Email"
  }
};

const navToggle = document.querySelector('.nav-toggle');
const navLinks = document.getElementById('navLinks');
const themeToggle = document.getElementById('themeToggle');
const languageSelect = document.getElementById('languageSelect');
const modal = document.getElementById('enquiryModal');
const openButtons = document.querySelectorAll('.open-enquiry');
const closeButtons = document.querySelectorAll('[data-close-modal]');
const enquiryForm = document.getElementById('enquiryForm');

function setLanguage(lang) {
  const dict = translations[lang] || translations.en;
  document.documentElement.lang = lang;
  document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr';
  document.querySelectorAll('[data-i18n]').forEach(el => {
    const key = el.getAttribute('data-i18n');
    if (dict[key]) el.textContent = dict[key];
  });
  localStorage.setItem('dcl_lang', lang);
}

function setTheme(theme) {
  document.body.classList.toggle('dark', theme === 'dark');
  localStorage.setItem('dcl_theme', theme);
}

if (navToggle && navLinks) {
  navToggle.addEventListener('click', () => {
    const open = navLinks.classList.toggle('active');
    navToggle.setAttribute('aria-expanded', String(open));
  });
  navLinks.querySelectorAll('a').forEach(link => link.addEventListener('click', () => {
    navLinks.classList.remove('active');
    navToggle.setAttribute('aria-expanded', 'false');
  }));
}

if (themeToggle) {
  themeToggle.addEventListener('click', () => {
    setTheme(document.body.classList.contains('dark') ? 'light' : 'dark');
  });
}

if (languageSelect) {
  languageSelect.addEventListener('change', (e) => setLanguage(e.target.value));
}

function openModal() {
  modal.classList.add('active');
  modal.setAttribute('aria-hidden', 'false');
  document.body.style.overflow = 'hidden';
}
function closeModal() {
  modal.classList.remove('active');
  modal.setAttribute('aria-hidden', 'true');
  document.body.style.overflow = '';
}
openButtons.forEach(button => button.addEventListener('click', openModal));
closeButtons.forEach(button => button.addEventListener('click', closeModal));
document.addEventListener('keydown', e => {
  if (e.key === 'Escape' && modal.classList.contains('active')) closeModal();
});

if (enquiryForm) {
  enquiryForm.addEventListener('submit', event => {
    event.preventDefault();
    const data = new FormData(enquiryForm);
    const name = encodeURIComponent(data.get('name'));
    const contact = encodeURIComponent(data.get('contact'));
    const message = encodeURIComponent(data.get('message'));
    const subject = encodeURIComponent('Website Enquiry - Doha Call Line');
    const body = `Name:%20${name}%0AEmail%20/%20Phone:%20${contact}%0A%0AMessage:%0A${message}`;
    window.location.href = `mailto:info@dohacallline.com?subject=${subject}&body=${body}`;
  });
}

// Hero slider
const heroSlides = document.querySelectorAll('.hero-bg');
let slideIndex = 0;
setInterval(() => {
  if (!heroSlides.length) return;
  heroSlides[slideIndex].classList.remove('active');
  slideIndex = (slideIndex + 1) % heroSlides.length;
  heroSlides[slideIndex].classList.add('active');
}, 4800);

// Smooth reveal animation
const revealObserver = new IntersectionObserver(entries => {
  entries.forEach(entry => {
    if (entry.isIntersecting) {
      entry.target.classList.add('visible');
      revealObserver.unobserve(entry.target);
    }
  });
}, { threshold: 0.12, rootMargin: '0px 0px -40px 0px' });

document.querySelectorAll('.reveal').forEach(el => revealObserver.observe(el));

// Initial settings
const savedTheme = localStorage.getItem('dcl_theme') || 'light';
const savedLang = localStorage.getItem('dcl_lang') || 'en';
setTheme(savedTheme);
if (languageSelect) languageSelect.value = savedLang;
setLanguage(savedLang);
