
const translations = {
  "en": {
    "nav_about": "About Us",
    "nav_services": "Services",
    "nav_projects": "Projects",
    "nav_clients": "Clients",
    "nav_contact": "Contact Us",
    "btn_enquiry": "Send Enquiry",
    "hero_eyebrow": "Engineering Comfort. Building Excellence.",
    "hero_title": "Integrated Engineering Solutions You Can Trust",
    "hero_text": "Delivering high-quality HVAC, Civil, MEP and Interior Decoration solutions with safety, integrity and unmatched performance.",
    "btn_services": "Our Services",
    "btn_projects": "Explore Projects",
    "pill_hvac": "HVAC Solutions",
    "pill_civil": "Civil Works",
    "pill_mep": "MEP Services",
    "pill_interior": "Interior Decoration",
    "hero_card_title": "Qatar-based engineering partner",
    "hero_card_text": "Built for residential, commercial and industrial project delivery.",
    "project_hvac_label": "HVAC Projects",
    "project_hvac_title": "Central Chilled Water Plant",
    "project_hvac_text": "AHU/FAHU, ducting works, VRF/VRV systems, testing and balancing.",
    "project_civil_label": "Civil Projects",
    "project_civil_title": "Structural & Concrete Works",
    "project_civil_text": "Concrete, block work, masonry, waterproofing and external finishes.",
    "project_mep_label": "MEP Projects",
    "project_mep_title": "Electrical & Plumbing Systems",
    "project_mep_text": "Power distribution, lighting, drainage systems, BMS and control systems.",
    "project_interior_label": "Decoration Projects",
    "project_interior_title": "Fit-Out & Finishing Works",
    "project_interior_text": "Gypsum ceiling, painting, wall tiling, flooring, joinery and carpentry.",
    "about_eyebrow": "About Doha Call Line (DCL)",
    "about_title": "Engineering solutions that build better futures.",
    "about_text_1": "Doha Call Line is a Qatar-based multidisciplinary company providing HVAC Solutions, Civil Works, MEP Services and Interior Decoration for residential, commercial and industrial projects.",
    "about_text_2": "With over a decade of experience, DCL has grown from a trusted cooling solutions provider to a reliable engineering and construction partner known for quality, safety and timely delivery.",
    "stat_years": "Years Experience",
    "stat_projects": "Projects Completed",
    "stat_team": "Skilled Professionals",
    "vision_title": "Vision",
    "vision_text": "To become a leading engineering and construction service provider in Qatar, recognized for quality, innovation, reliability and sustainable solutions.",
    "mission_title": "Mission",
    "mission_text": "To deliver high-quality HVAC, Civil, MEP and Interior Decoration solutions through expertise, integrity and commitment to exceeding client expectations.",
    "values_eyebrow": "Core Values",
    "values_title": "Safe, quality and sustainable delivery.",
    "value_quality": "Quality",
    "value_quality_text": "We deliver quality workmanship in everything we do.",
    "value_safety": "Safety",
    "value_safety_text": "We prioritize safety for our people, clients and projects.",
    "value_integrity": "Integrity",
    "value_integrity_text": "We operate with honesty, transparency and fairness.",
    "value_innovation": "Innovation",
    "value_innovation_text": "We embrace new ideas and technology to deliver better solutions.",
    "value_sustainability": "Sustainability",
    "value_sustainability_text": "We are committed to environmental responsibility and a sustainable future.",
    "value_teamwork": "Teamwork",
    "value_teamwork_text": "We believe in collaboration to achieve excellence together.",
    "services_eyebrow": "Discover Our Services",
    "services_title": "Complete engineering services under one platform.",
    "services_text": "Clear scopes, coordinated execution and reliable project delivery across HVAC, Civil, MEP and Interior Decoration.",
    "svc_hvac_title": "HVAC Solutions",
    "svc_hvac_text": "Design, supply, installation, testing and maintenance of air conditioning, ventilation and refrigeration systems.",
    "svc_civil_title": "Civil Works",
    "svc_civil_text": "Structural works, concrete works, masonry, plastering, tiling, and all related civil construction services.",
    "svc_mep_title": "MEP Services",
    "svc_mep_text": "Mechanical, electrical & plumbing services including HVAC, electrical systems, plumbing, firefighting and more.",
    "svc_interior_title": "Interior Decoration",
    "svc_interior_text": "Interior design, fit-out, ceiling, flooring, painting, partitions, lighting and all interior decoration works.",
    "solutions_eyebrow": "Integrated Engineering Solutions",
    "solutions_title": "We build more than projects — we build trust.",
    "sol_design": "Design & Engineering",
    "sol_design_text": "Technical drawings, calculations and engineering documentation.",
    "sol_procurement": "Procurement & Supply",
    "sol_procurement_text": "Material sourcing, supplier coordination and project logistics.",
    "sol_construction": "Construction & Installation",
    "sol_construction_text": "Site execution by skilled teams with quality and safety control.",
    "sol_testing": "Testing & Commissioning",
    "sol_testing_text": "Performance verification, inspection and handover readiness.",
    "sol_maintenance": "Operation & Maintenance",
    "sol_maintenance_text": "Reliable after-service support and preventive maintenance.",
    "sol_turnkey": "Turnkey Project Delivery",
    "sol_turnkey_text": "One platform from concept to completion.",
    "iso_quality": "Quality Management",
    "iso_env": "Environmental Management",
    "iso_safety": "Occupational Health & Safety",
    "team_eyebrow": "Team & Organization",
    "team_title": "Organized for efficient project delivery.",
    "team_text": "Our organizational structure is designed to ensure efficient project delivery, clear communication and accountability at every level.",
    "org_general": "General Manager",
    "org_engineers": "Engineers",
    "org_engineers_text": "Technical design, calculations, project planning and documentation.",
    "org_pm": "Project Managers",
    "org_pm_text": "Planning, budget, scheduling, client coordination and risk management.",
    "org_supervisors": "Supervisors",
    "org_supervisors_text": "Site supervision, quality monitoring and safe execution of works.",
    "org_technicians": "Technicians",
    "org_technicians_text": "Installation, testing, commissioning, operation and maintenance.",
    "org_support": "Support Functions",
    "org_support_text": "Admin, HR, procurement, QA/QC, finance and HSE support.",
    "hse_badge": "Safety First",
    "hse_title": "Health, Safety & Quality",
    "hse_text": "We are committed to the health, safety and well-being of our people, our clients and the communities in which we work.",
    "hse_ppe": "PPE Compliance",
    "hse_ppe_text": "Mandatory PPE, helmets, safety shoes, gloves and goggles.",
    "hse_risk": "Risk Assessment",
    "hse_risk_text": "Hazard identification, risk evaluation and control measures.",
    "hse_toolbox": "Toolbox Talks",
    "hse_toolbox_text": "Daily safety briefing, task planning and worker awareness.",
    "hse_emergency": "Emergency Response",
    "hse_emergency_text": "Emergency procedures, evacuation plans and first aid readiness.",
    "hse_quality": "Quality Inspections",
    "hse_quality_text": "Material inspections, method statements and final testing.",
    "hse_record": "Record & Reporting",
    "hse_record_text": "Inspection records, NCR tracking and corrective actions.",
    "why_eyebrow": "Why Choose Us",
    "why_title": "Reliable delivery from planning to commissioning.",
    "why_exp": "25+ Years Experience",
    "why_exp_text": "Extensive experience across HVAC, Civil, MEP and fit-out projects.",
    "why_manpower": "Skilled Technical Manpower",
    "why_manpower_text": "Qualified engineers, supervisors, technicians and skilled workers.",
    "why_qaqc": "Quality Assurance & QA/QC",
    "why_qaqc_text": "Strict compliance with specifications, inspection and standards.",
    "why_time": "On-Time Project Delivery",
    "why_time_text": "Efficient planning, coordination and execution without compromising quality.",
    "why_hse": "HSE & Safety Commitment",
    "why_hse_text": "Risk assessment, toolbox talks and safe working procedures.",
    "why_integrated": "Integrated Engineering Solutions",
    "why_integrated_text": "HVAC, Civil, MEP and Interior services under one coordinated platform.",
    "projects_eyebrow": "Our Projects",
    "projects_title": "Project capabilities across every discipline.",
    "port_hvac": "HVAC Installation",
    "port_civil": "Civil Construction",
    "port_mep": "MEP Systems",
    "port_interior": "Interior Fit-Out",
    "clients_eyebrow": "Major Clients",
    "clients_title": "Trusted by leading organizations across Qatar.",
    "client_qatar": "Delivered comprehensive MEP solutions for various museum facilities, ensuring world-class comfort, efficiency, and reliability.",
    "client_redco": "Executed HVAC, plumbing, and MEP works for multiple residential, commercial, and infrastructure projects with high quality and on-time delivery.",
    "client_secc": "Partnered on large-scale infrastructure and building projects, providing complete MEP and civil engineering solutions.",
    "client_aljaber": "Delivered a wide range of MEP services across critical and commercial projects, meeting the highest standards of safety, quality, and performance.",
    "contact_eyebrow": "Contact Us",
    "contact_title": "Let’s build the future together.",
    "contact_text": "Have a project in mind? Get in touch with us and we will deliver the right engineering solution.",
    "address_label": "Address",
    "phone_label": "Mobile",
    "email_label": "Emails",
    "footer_tagline": "Engineering Comfort. Building Excellence.",

    "overview_hvac_title": "HVAC PROJECT",
    "overview_hvac_text": "Design, supply, installation, testing and maintenance of air conditioning, ventilation and refrigeration systems.",
    "overview_civil_title": "CIVIL PROJECT",
    "overview_civil_text": "Structural works, concrete works, masonry, plastering, tiling, and all related civil construction services.",
    "overview_mep_title": "MEP PROJECT",
    "overview_mep_text": "Mechanical, electrical & plumbing services including HVAC, electrical systems, plumbing, firefighting and more.",
    "overview_interior_title": "DECORATION PROJECT",
    "overview_interior_text": "Interior design, fit-out, ceiling, flooring, painting, partitions, lighting and all interior decoration works.",
    "svc_hvac_p1": "Load calculating & system design",
    "svc_hvac_p2": "VRF/VRV, chilled water & DX systems",
    "svc_hvac_p3": "AHU, FCU, FAHU & RAHU installation",
    "svc_hvac_p4": "Ducting, insulation & air distribution",
    "svc_hvac_p5": "Testing, commissioning & maintenance",
    "svc_civil_p1": "Structural works (RCC, steel & masonry)",
    "svc_civil_p2": "Concrete works & formwork",
    "svc_civil_p3": "Roads, paving & infrastructure works",
    "svc_civil_p4": "Excavation, backfilling & compaction",
    "svc_civil_p5": "Finishing & refurbishment works",
    "svc_mep_p1": "Electrical power distribution (LV/MV)",
    "svc_mep_p2": "Lighting, emergency & exterior lighting",
    "svc_mep_p3": "Plumbing, sanitary systems",
    "svc_mep_p4": "Fire alarm, fire fighting & Gas systems",
    "svc_mep_p5": "BMS, ELV, Data & Communication",
    "svc_mep_p6": "Testing, commissioning & maintenance",
    "svc_interior_p1": "Interior design & space planning",
    "svc_interior_p2": "Gypsum works, partitions & ceilings",
    "svc_interior_p3": "Flooring (tiles, marble, vinyl, carpet, etc)",
    "svc_interior_p4": "Painting, wallpaper & wall finishes",
    "svc_interior_p5": "Joinery, carpentry & custom furniture",
    "svc_interior_p6": "Lighting design & decorative works",
    "tab_hvac": "HVAC Projects",
    "tab_civil": "Civil Works",
    "tab_mep": "MEP Projects",
    "tab_decoration": "Decoration Projects",
    "project_panel_hvac_title": "HVAC solutions for efficient and reliable building comfort.",
    "project_panel_hvac_text": "From central chilled water plants to VRF/VRV systems, AHU/FAHU installation, ducting, testing and maintenance.",
    "project_panel_civil_title": "Civil construction works delivered with safety and accuracy.",
    "project_panel_civil_text": "Structural works, concrete works, block work, masonry, waterproofing, finishing and related civil construction services.",
    "project_panel_mep_title": "Integrated mechanical, electrical and plumbing systems.",
    "project_panel_mep_text": "Electrical power distribution, lighting, LV systems, plumbing, drainage, BMS and control systems.",
    "project_panel_decoration_title": "Interior fit-out and decoration works with refined finishing.",
    "project_panel_decoration_text": "Gypsum ceilings, partitions, painting, flooring, wall tiling, joinery, carpentry and decorative lighting.",
    "hvac_img_1": "Central Chilled Water Plant",
    "hvac_img_2": "AHU / FAHU Installations",
    "hvac_img_3": "Ducting Works (GI & Fabric)",
    "hvac_img_4": "VRF / VRV Systems",
    "civil_img_1": "Concrete Works",
    "civil_img_2": "Structural Works",
    "civil_img_3": "Block Work & Masonry",
    "civil_img_4": "Waterproofing Works",
    "mep_img_1": "Electrical Power Distribution",
    "mep_img_2": "Lighting & LV Systems",
    "mep_img_3": "Plumbing & Drainage Systems",
    "mep_img_4": "BMS & Control Systems",
    "decor_img_1": "Gypsum Ceiling & Partitions",
    "decor_img_2": "Painting Works",
    "decor_img_3": "Flooring & Wall Tiling",
    "decor_img_4": "Joinery & Carpentry",
    "modal_eyebrow": "Quick Contact",
    "modal_title": "Send Enquiry",
    "form_name": "Your Name",
    "form_contact": "Email / Phone",
    "form_message": "Message",
    "form_send": "Send Email",
    "values_text": "We are dedicated to delivering safe, quality and sustainable projects that create long term value for our clients and community.",
    "org_leadership_title": "Leadership & Strategic Oversight",
    "org_leadership_text": "Overall direction, business strategy, stakeholder coordination and project performance management."
},
  "zh": {
    "nav_about": "关于我们",
    "nav_services": "服务",
    "nav_projects": "项目",
    "nav_clients": "客户",
    "nav_contact": "联系我们",
    "btn_enquiry": "发送询盘",
    "hero_eyebrow": "工程舒适，筑造卓越。",
    "hero_title": "值得信赖的一体化工程解决方案",
    "hero_text": "以安全、诚信和卓越表现提供高质量HVAC、土建、MEP和室内装饰解决方案。",
    "btn_services": "我们的服务",
    "btn_projects": "查看项目",
    "pill_hvac": "暖通空调解决方案",
    "pill_civil": "土建工程",
    "pill_mep": "机电服务",
    "pill_interior": "室内装饰",
    "hero_card_title": "卡塔尔本地工程合作伙伴",
    "hero_card_text": "服务住宅、商业和工业项目交付。",
    "project_hvac_label": "HVAC Projects",
    "project_hvac_title": "Central Chilled Water Plant",
    "project_hvac_text": "AHU/FAHU, ducting works, VRF/VRV systems, testing and balancing.",
    "project_civil_label": "Civil Projects",
    "project_civil_title": "Structural & Concrete Works",
    "project_civil_text": "Concrete, block work, masonry, waterproofing and external finishes.",
    "project_mep_label": "MEP Projects",
    "project_mep_title": "Electrical & Plumbing Systems",
    "project_mep_text": "Power distribution, lighting, drainage systems, BMS and control systems.",
    "project_interior_label": "Decoration Projects",
    "project_interior_title": "Fit-Out & Finishing Works",
    "project_interior_text": "Gypsum ceiling, painting, wall tiling, flooring, joinery and carpentry.",
    "about_eyebrow": "关于 DOHA CALL LINE (DCL)",
    "about_title": "建设更美好未来的工程解决方案。",
    "about_text_1": "Doha Call Line 是一家位于卡塔尔的多专业公司，为住宅、商业和工业项目提供 HVAC、土建、MEP 和室内装饰服务。",
    "about_text_2": "凭借十多年的经验，DCL 已发展成为以质量、安全和准时交付著称的工程与建设伙伴。",
    "stat_years": "年经验",
    "stat_projects": "完成项目",
    "stat_team": "专业人员",
    "vision_title": "愿景",
    "vision_text": "成为卡塔尔领先的工程和建设服务提供商，以质量、创新、可靠性和可持续解决方案著称。",
    "mission_title": "使命",
    "mission_text": "通过专业、诚信和超越客户期望的承诺，提供高质量的 HVAC、土建、MEP 和室内装饰解决方案。",
    "values_eyebrow": "核心价值",
    "values_title": "安全、质量与可持续交付。",
    "value_quality": "质量",
    "value_quality_text": "我们在每项工作中都交付高质量工艺。",
    "value_safety": "安全",
    "value_safety_text": "我们重视员工、客户和项目的安全。",
    "value_integrity": "诚信",
    "value_integrity_text": "我们以诚实、透明和公平开展业务。",
    "value_innovation": "创新",
    "value_innovation_text": "我们采用新理念和技术提供更好的解决方案。",
    "value_sustainability": "可持续",
    "value_sustainability_text": "我们致力于环保责任和可持续未来。",
    "value_teamwork": "团队合作",
    "value_teamwork_text": "我们相信协作成就卓越。",
    "services_eyebrow": "探索我们的服务",
    "services_title": "一个平台提供完整工程服务。",
    "services_text": "清晰的服务范围、协同执行，以及覆盖 HVAC、土建、MEP 和室内装饰的可靠项目交付。",
    "svc_hvac_title": "暖通空调解决方案",
    "svc_hvac_text": "空调、通风和制冷系统的设计、供应、安装、测试和维护。",
    "svc_civil_title": "土建工程",
    "svc_civil_text": "结构工程、混凝土工程、砌体、抹灰、瓷砖以及相关土建施工服务。",
    "svc_mep_title": "机电服务",
    "svc_mep_text": "机械、电气和给排水服务，包括 HVAC、电气系统、管道、消防等。",
    "svc_interior_title": "室内装饰",
    "svc_interior_text": "室内设计、装修、天花、地面、油漆、隔断、照明及室内装饰工程。",
    "solutions_eyebrow": "一体化工程解决方案",
    "solutions_title": "我们不只建设项目，也建立信任。",
    "sol_design": "Design & Engineering",
    "sol_design_text": "Technical drawings, calculations and engineering documentation.",
    "sol_procurement": "Procurement & Supply",
    "sol_procurement_text": "Material sourcing, supplier coordination and project logistics.",
    "sol_construction": "Construction & Installation",
    "sol_construction_text": "Site execution by skilled teams with quality and safety control.",
    "sol_testing": "Testing & Commissioning",
    "sol_testing_text": "Performance verification, inspection and handover readiness.",
    "sol_maintenance": "Operation & Maintenance",
    "sol_maintenance_text": "Reliable after-service support and preventive maintenance.",
    "sol_turnkey": "Turnkey Project Delivery",
    "sol_turnkey_text": "One platform from concept to completion.",
    "iso_quality": "Quality Management",
    "iso_env": "Environmental Management",
    "iso_safety": "Occupational Health & Safety",
    "team_eyebrow": "团队与组织",
    "team_title": "为高效项目交付而组织。",
    "team_text": "我们的组织结构确保高效交付、清晰沟通和责任落实。",
    "org_general": "General Manager",
    "org_engineers": "Engineers",
    "org_engineers_text": "Technical design, calculations, project planning and documentation.",
    "org_pm": "Project Managers",
    "org_pm_text": "Planning, budget, scheduling, client coordination and risk management.",
    "org_supervisors": "Supervisors",
    "org_supervisors_text": "Site supervision, quality monitoring and safe execution of works.",
    "org_technicians": "Technicians",
    "org_technicians_text": "Installation, testing, commissioning, operation and maintenance.",
    "org_support": "Support Functions",
    "org_support_text": "Admin, HR, procurement, QA/QC, finance and HSE support.",
    "hse_badge": "Safety First",
    "hse_title": "健康、安全与质量",
    "hse_text": "我们致力于员工、客户及社区的健康、安全和福祉。",
    "hse_ppe": "PPE Compliance",
    "hse_ppe_text": "Mandatory PPE, helmets, safety shoes, gloves and goggles.",
    "hse_risk": "Risk Assessment",
    "hse_risk_text": "Hazard identification, risk evaluation and control measures.",
    "hse_toolbox": "Toolbox Talks",
    "hse_toolbox_text": "Daily safety briefing, task planning and worker awareness.",
    "hse_emergency": "Emergency Response",
    "hse_emergency_text": "Emergency procedures, evacuation plans and first aid readiness.",
    "hse_quality": "Quality Inspections",
    "hse_quality_text": "Material inspections, method statements and final testing.",
    "hse_record": "Record & Reporting",
    "hse_record_text": "Inspection records, NCR tracking and corrective actions.",
    "why_eyebrow": "为什么选择我们",
    "why_title": "从规划到调试的可靠交付。",
    "why_exp": "25+ Years Experience",
    "why_exp_text": "Extensive experience across HVAC, Civil, MEP and fit-out projects.",
    "why_manpower": "Skilled Technical Manpower",
    "why_manpower_text": "Qualified engineers, supervisors, technicians and skilled workers.",
    "why_qaqc": "Quality Assurance & QA/QC",
    "why_qaqc_text": "Strict compliance with specifications, inspection and standards.",
    "why_time": "On-Time Project Delivery",
    "why_time_text": "Efficient planning, coordination and execution without compromising quality.",
    "why_hse": "HSE & Safety Commitment",
    "why_hse_text": "Risk assessment, toolbox talks and safe working procedures.",
    "why_integrated": "Integrated Engineering Solutions",
    "why_integrated_text": "HVAC, Civil, MEP and Interior services under one coordinated platform.",
    "projects_eyebrow": "我们的项目",
    "projects_title": "覆盖各专业领域的项目能力。",
    "port_hvac": "HVAC Installation",
    "port_civil": "Civil Construction",
    "port_mep": "MEP Systems",
    "port_interior": "Interior Fit-Out",
    "clients_eyebrow": "主要客户",
    "clients_title": "受到卡塔尔领先机构的信赖。",
    "client_qatar": "Delivered comprehensive MEP solutions for various museum facilities, ensuring world-class comfort, efficiency, and reliability.",
    "client_redco": "Executed HVAC, plumbing, and MEP works for multiple residential, commercial, and infrastructure projects with high quality and on-time delivery.",
    "client_secc": "Partnered on large-scale infrastructure and building projects, providing complete MEP and civil engineering solutions.",
    "client_aljaber": "Delivered a wide range of MEP services across critical and commercial projects, meeting the highest standards of safety, quality, and performance.",
    "contact_eyebrow": "联系我们",
    "contact_title": "让我们一起建设未来。",
    "contact_text": "如果您有项目需求，请联系我们，我们将提供合适的工程解决方案。",
    "address_label": "Address",
    "phone_label": "Mobile",
    "email_label": "Emails",
    "footer_tagline": "工程舒适，筑造卓越。",

    "overview_hvac_title": "HVAC 项目",
    "overview_hvac_text": "空调、通风和制冷系统的设计、供应、安装、测试和维护。",
    "overview_civil_title": "土建项目",
    "overview_civil_text": "结构工程、混凝土工程、砌体、抹灰、瓷砖以及相关土建施工服务。",
    "overview_mep_title": "MEP 项目",
    "overview_mep_text": "机械、电气和给排水服务，包括 HVAC、电气系统、管道、消防等。",
    "overview_interior_title": "室内装饰项目",
    "overview_interior_text": "室内设计、装修、天花、地面、油漆、隔断、照明及室内装饰工程。",
    "svc_hvac_p1": "负荷计算与系统设计",
    "svc_hvac_p2": "VRF/VRV、冷冻水与 DX 系统",
    "svc_hvac_p3": "AHU、FCU、FAHU 与 RAHU 安装",
    "svc_hvac_p4": "风管、保温与空气分配",
    "svc_hvac_p5": "测试、调试与维护",
    "svc_civil_p1": "结构工程（RCC、钢结构与砌体）",
    "svc_civil_p2": "混凝土工程与模板工程",
    "svc_civil_p3": "道路、铺装与基础设施工程",
    "svc_civil_p4": "开挖、回填与压实",
    "svc_civil_p5": "精装修与翻新工程",
    "svc_mep_p1": "电力配电（LV/MV）",
    "svc_mep_p2": "照明、应急照明与室外照明",
    "svc_mep_p3": "给排水与卫生系统",
    "svc_mep_p4": "火灾报警、消防与燃气系统",
    "svc_mep_p5": "BMS、ELV、数据与通信",
    "svc_mep_p6": "测试、调试与维护",
    "svc_interior_p1": "室内设计与空间规划",
    "svc_interior_p2": "石膏工程、隔断与天花",
    "svc_interior_p3": "地面工程（瓷砖、大理石、乙烯基、地毯等）",
    "svc_interior_p4": "油漆、墙纸与墙面饰面",
    "svc_interior_p5": "木作、木工与定制家具",
    "svc_interior_p6": "照明设计与装饰工程",
    "tab_hvac": "HVAC 项目",
    "tab_civil": "土建工程",
    "tab_mep": "MEP 项目",
    "tab_decoration": "装饰项目",
    "project_panel_hvac_title": "高效可靠建筑舒适性的 HVAC 解决方案。",
    "project_panel_hvac_text": "从中央冷冻水机房到 VRF/VRV 系统、AHU/FAHU 安装、风管、测试和维护。",
    "project_panel_civil_title": "以安全与精度交付土建工程。",
    "project_panel_civil_text": "结构工程、混凝土、砌块砌体、防水、收尾及相关土建服务。",
    "project_panel_mep_title": "综合机械、电气与给排水系统。",
    "project_panel_mep_text": "电力配电、照明、低压系统、给排水、BMS 和控制系统。",
    "project_panel_decoration_title": "精致收口的室内装修与装饰工程。",
    "project_panel_decoration_text": "石膏天花、隔断、油漆、地面、墙砖、木作、木工和装饰照明。",
    "hvac_img_1": "中央冷冻水机房",
    "hvac_img_2": "AHU / FAHU 安装",
    "hvac_img_3": "风管工程（GI 与 Fabric）",
    "hvac_img_4": "VRF / VRV 系统",
    "civil_img_1": "混凝土工程",
    "civil_img_2": "结构工程",
    "civil_img_3": "砌块与砌体工程",
    "civil_img_4": "防水工程",
    "mep_img_1": "电力配电",
    "mep_img_2": "照明与 LV 系统",
    "mep_img_3": "给排水系统",
    "mep_img_4": "BMS 与控制系统",
    "decor_img_1": "石膏天花与隔断",
    "decor_img_2": "油漆工程",
    "decor_img_3": "地面与墙面瓷砖",
    "decor_img_4": "木作与木工",
    "modal_eyebrow": "Quick Contact",
    "modal_title": "发送询盘",
    "form_name": "Your Name",
    "form_contact": "Email / Phone",
    "form_message": "Message",
    "form_send": "Send Email",
    "values_text": "我们致力于交付安全、优质且可持续的项目，为客户与社区创造长期价值。",
    "projects_text": "选择项目类别查看详情和项目图片。",
    "org_leadership_title": "领导与战略监督",
    "org_leadership_text": "整体方向、业务战略、利益相关方协调与项目绩效管理。"
},
  "fr": {
    "nav_about": "À propos",
    "nav_services": "Services",
    "nav_projects": "Projets",
    "nav_clients": "Clients",
    "nav_contact": "Contact",
    "btn_enquiry": "Envoyer une demande",
    "hero_eyebrow": "Confort d’ingénierie. Excellence de construction.",
    "hero_title": "Solutions d’ingénierie intégrées de confiance",
    "hero_text": "Nous fournissons des solutions HVAC, génie civil, MEP et décoration intérieure avec sécurité, intégrité et performance.",
    "btn_services": "Nos services",
    "btn_projects": "Voir les projets",
    "pill_hvac": "Solutions HVAC",
    "pill_civil": "Travaux civils",
    "pill_mep": "Services MEP",
    "pill_interior": "Décoration intérieure",
    "hero_card_title": "Partenaire d’ingénierie basé au Qatar",
    "hero_card_text": "Conçu pour les projets résidentiels, commerciaux et industriels.",
    "project_hvac_label": "HVAC Projects",
    "project_hvac_title": "Central Chilled Water Plant",
    "project_hvac_text": "AHU/FAHU, ducting works, VRF/VRV systems, testing and balancing.",
    "project_civil_label": "Civil Projects",
    "project_civil_title": "Structural & Concrete Works",
    "project_civil_text": "Concrete, block work, masonry, waterproofing and external finishes.",
    "project_mep_label": "MEP Projects",
    "project_mep_title": "Electrical & Plumbing Systems",
    "project_mep_text": "Power distribution, lighting, drainage systems, BMS and control systems.",
    "project_interior_label": "Decoration Projects",
    "project_interior_title": "Fit-Out & Finishing Works",
    "project_interior_text": "Gypsum ceiling, painting, wall tiling, flooring, joinery and carpentry.",
    "about_eyebrow": "À propos de Doha Call Line (DCL)",
    "about_title": "Des solutions d’ingénierie pour construire un avenir meilleur.",
    "about_text_1": "Doha Call Line est une entreprise multidisciplinaire basée au Qatar fournissant des solutions HVAC, travaux civils, MEP et décoration intérieure.",
    "about_text_2": "Avec plus d’une décennie d’expérience, DCL est devenue un partenaire reconnu pour la qualité, la sécurité et le respect des délais.",
    "stat_years": "Années d’expérience",
    "stat_projects": "Projets réalisés",
    "stat_team": "Professionnels qualifiés",
    "vision_title": "Vision",
    "vision_text": "Devenir un fournisseur leader de services d’ingénierie et de construction au Qatar, reconnu pour la qualité, l’innovation et la durabilité.",
    "mission_title": "Mission",
    "mission_text": "Fournir des solutions HVAC, Civiles, MEP et décoration intérieure de haute qualité avec expertise, intégrité et engagement.",
    "values_eyebrow": "Valeurs clés",
    "values_title": "Livraison sûre, qualitative et durable.",
    "value_quality": "Qualité",
    "value_quality_text": "Nous livrons un travail de qualité dans tout ce que nous faisons.",
    "value_safety": "Sécurité",
    "value_safety_text": "Nous privilégions la sécurité de nos équipes, clients et projets.",
    "value_integrity": "Intégrité",
    "value_integrity_text": "Nous travaillons avec honnêteté, transparence et équité.",
    "value_innovation": "Innovation",
    "value_innovation_text": "Nous adoptons les nouvelles idées et technologies.",
    "value_sustainability": "Durabilité",
    "value_sustainability_text": "Nous sommes engagés envers la responsabilité environnementale.",
    "value_teamwork": "Travail d’équipe",
    "value_teamwork_text": "Nous croyons à la collaboration pour atteindre l’excellence.",
    "services_eyebrow": "Découvrez nos services",
    "services_title": "Des services d’ingénierie complets sur une seule plateforme.",
    "services_text": "Des périmètres clairs, une exécution coordonnée et une livraison fiable pour HVAC, génie civil, MEP et décoration intérieure.",
    "svc_hvac_title": "Solutions HVAC",
    "svc_hvac_text": "Conception, fourniture, installation, essais et maintenance des systèmes de climatisation, ventilation et réfrigération.",
    "svc_civil_title": "Travaux civils",
    "svc_civil_text": "Travaux structurels, béton, maçonnerie, plâtrerie, carrelage et services de construction civile associés.",
    "svc_mep_title": "Services MEP",
    "svc_mep_text": "Services mécaniques, électriques et plomberie, incluant HVAC, systèmes électriques, plomberie, lutte incendie et plus.",
    "svc_interior_title": "Décoration intérieure",
    "svc_interior_text": "Design intérieur, fit-out, plafonds, sols, peinture, cloisons, éclairage et décoration intérieure.",
    "solutions_eyebrow": "Solutions d’ingénierie intégrées",
    "solutions_title": "Nous construisons plus que des projets — nous construisons la confiance.",
    "sol_design": "Design & Engineering",
    "sol_design_text": "Technical drawings, calculations and engineering documentation.",
    "sol_procurement": "Procurement & Supply",
    "sol_procurement_text": "Material sourcing, supplier coordination and project logistics.",
    "sol_construction": "Construction & Installation",
    "sol_construction_text": "Site execution by skilled teams with quality and safety control.",
    "sol_testing": "Testing & Commissioning",
    "sol_testing_text": "Performance verification, inspection and handover readiness.",
    "sol_maintenance": "Operation & Maintenance",
    "sol_maintenance_text": "Reliable after-service support and preventive maintenance.",
    "sol_turnkey": "Turnkey Project Delivery",
    "sol_turnkey_text": "One platform from concept to completion.",
    "iso_quality": "Quality Management",
    "iso_env": "Environmental Management",
    "iso_safety": "Occupational Health & Safety",
    "team_eyebrow": "Équipe & Organisation",
    "team_title": "Organisés pour une livraison efficace des projets.",
    "team_text": "Notre structure garantit une livraison efficace, une communication claire et la responsabilité.",
    "org_general": "General Manager",
    "org_engineers": "Engineers",
    "org_engineers_text": "Technical design, calculations, project planning and documentation.",
    "org_pm": "Project Managers",
    "org_pm_text": "Planning, budget, scheduling, client coordination and risk management.",
    "org_supervisors": "Supervisors",
    "org_supervisors_text": "Site supervision, quality monitoring and safe execution of works.",
    "org_technicians": "Technicians",
    "org_technicians_text": "Installation, testing, commissioning, operation and maintenance.",
    "org_support": "Support Functions",
    "org_support_text": "Admin, HR, procurement, QA/QC, finance and HSE support.",
    "hse_badge": "Safety First",
    "hse_title": "Santé, sécurité & qualité",
    "hse_text": "Nous nous engageons pour la santé, la sécurité et le bien-être de nos équipes, clients et communautés.",
    "hse_ppe": "PPE Compliance",
    "hse_ppe_text": "Mandatory PPE, helmets, safety shoes, gloves and goggles.",
    "hse_risk": "Risk Assessment",
    "hse_risk_text": "Hazard identification, risk evaluation and control measures.",
    "hse_toolbox": "Toolbox Talks",
    "hse_toolbox_text": "Daily safety briefing, task planning and worker awareness.",
    "hse_emergency": "Emergency Response",
    "hse_emergency_text": "Emergency procedures, evacuation plans and first aid readiness.",
    "hse_quality": "Quality Inspections",
    "hse_quality_text": "Material inspections, method statements and final testing.",
    "hse_record": "Record & Reporting",
    "hse_record_text": "Inspection records, NCR tracking and corrective actions.",
    "why_eyebrow": "Pourquoi nous choisir",
    "why_title": "Une livraison fiable de la planification à la mise en service.",
    "why_exp": "25+ Years Experience",
    "why_exp_text": "Extensive experience across HVAC, Civil, MEP and fit-out projects.",
    "why_manpower": "Skilled Technical Manpower",
    "why_manpower_text": "Qualified engineers, supervisors, technicians and skilled workers.",
    "why_qaqc": "Quality Assurance & QA/QC",
    "why_qaqc_text": "Strict compliance with specifications, inspection and standards.",
    "why_time": "On-Time Project Delivery",
    "why_time_text": "Efficient planning, coordination and execution without compromising quality.",
    "why_hse": "HSE & Safety Commitment",
    "why_hse_text": "Risk assessment, toolbox talks and safe working procedures.",
    "why_integrated": "Integrated Engineering Solutions",
    "why_integrated_text": "HVAC, Civil, MEP and Interior services under one coordinated platform.",
    "projects_eyebrow": "Nos projets",
    "projects_title": "Capacités projet dans chaque discipline.",
    "port_hvac": "HVAC Installation",
    "port_civil": "Civil Construction",
    "port_mep": "MEP Systems",
    "port_interior": "Interior Fit-Out",
    "clients_eyebrow": "Principaux clients",
    "clients_title": "Reconnu par les grandes organisations au Qatar.",
    "client_qatar": "Delivered comprehensive MEP solutions for various museum facilities, ensuring world-class comfort, efficiency, and reliability.",
    "client_redco": "Executed HVAC, plumbing, and MEP works for multiple residential, commercial, and infrastructure projects with high quality and on-time delivery.",
    "client_secc": "Partnered on large-scale infrastructure and building projects, providing complete MEP and civil engineering solutions.",
    "client_aljaber": "Delivered a wide range of MEP services across critical and commercial projects, meeting the highest standards of safety, quality, and performance.",
    "contact_eyebrow": "Contact",
    "contact_title": "Construisons l’avenir ensemble.",
    "contact_text": "Vous avez un projet? Contactez-nous et nous fournirons la solution d’ingénierie adaptée.",
    "address_label": "Address",
    "phone_label": "Mobile",
    "email_label": "Emails",
    "footer_tagline": "Confort d’ingénierie. Excellence de construction.",

    "overview_hvac_title": "PROJET HVAC",
    "overview_hvac_text": "Conception, fourniture, installation, essais et maintenance des systèmes de climatisation, ventilation et réfrigération.",
    "overview_civil_title": "PROJET GÉNIE CIVIL",
    "overview_civil_text": "Travaux structurels, béton, maçonnerie, plâtrerie, carrelage et services de construction civile associés.",
    "overview_mep_title": "PROJET MEP",
    "overview_mep_text": "Services mécaniques, électriques et plomberie, incluant HVAC, systèmes électriques, plomberie, lutte incendie et plus.",
    "overview_interior_title": "PROJET DÉCORATION",
    "overview_interior_text": "Design intérieur, fit-out, plafonds, sols, peinture, cloisons, éclairage et décoration intérieure.",
    "svc_hvac_p1": "Calcul des charges et conception système",
    "svc_hvac_p2": "Systèmes VRF/VRV, eau glacée et DX",
    "svc_hvac_p3": "Installation AHU, FCU, FAHU et RAHU",
    "svc_hvac_p4": "Gaines, isolation et distribution d’air",
    "svc_hvac_p5": "Essais, mise en service et maintenance",
    "svc_civil_p1": "Travaux structurels (RCC, acier et maçonnerie)",
    "svc_civil_p2": "Béton et coffrage",
    "svc_civil_p3": "Routes, pavage et infrastructures",
    "svc_civil_p4": "Excavation, remblai et compactage",
    "svc_civil_p5": "Finitions et rénovation",
    "svc_mep_p1": "Distribution électrique (BT/MT)",
    "svc_mep_p2": "Éclairage, urgence et extérieur",
    "svc_mep_p3": "Plomberie et sanitaires",
    "svc_mep_p4": "Alarme incendie, lutte incendie et gaz",
    "svc_mep_p5": "BMS, ELV, données et communication",
    "svc_mep_p6": "Essais, mise en service et maintenance",
    "svc_interior_p1": "Design intérieur et planification d’espace",
    "svc_interior_p2": "Gypsum, cloisons et plafonds",
    "svc_interior_p3": "Sols (carrelage, marbre, vinyle, moquette, etc.)",
    "svc_interior_p4": "Peinture, papier peint et finitions murales",
    "svc_interior_p5": "Menuiserie, charpenterie et mobilier sur mesure",
    "svc_interior_p6": "Conception d’éclairage et travaux décoratifs",
    "tab_hvac": "Projets HVAC",
    "tab_civil": "Génie civil",
    "tab_mep": "Projets MEP",
    "tab_decoration": "Décoration",
    "project_panel_hvac_title": "Solutions HVAC pour un confort fiable et efficace.",
    "project_panel_hvac_text": "Des centrales d’eau glacée aux systèmes VRF/VRV, AHU/FAHU, gaines, essais et maintenance.",
    "project_panel_civil_title": "Travaux civils livrés avec sécurité et précision.",
    "project_panel_civil_text": "Structures, béton, blocs, maçonnerie, étanchéité, finitions et services civils associés.",
    "project_panel_mep_title": "Systèmes mécaniques, électriques et plomberie intégrés.",
    "project_panel_mep_text": "Distribution électrique, éclairage, systèmes BT, plomberie, drainage, BMS et contrôle.",
    "project_panel_decoration_title": "Fit-out intérieur avec finitions soignées.",
    "project_panel_decoration_text": "Plafonds gypsum, cloisons, peinture, sols, carrelage mural, menuiserie et éclairage décoratif.",
    "hvac_img_1": "Central Chilled Water Plant",
    "hvac_img_2": "Installations AHU / FAHU",
    "hvac_img_3": "Travaux de gaines (GI & Fabric)",
    "hvac_img_4": "Systèmes VRF / VRV",
    "civil_img_1": "Travaux béton",
    "civil_img_2": "Travaux structurels",
    "civil_img_3": "Blocs et maçonnerie",
    "civil_img_4": "Travaux d’étanchéité",
    "mep_img_1": "Distribution électrique",
    "mep_img_2": "Éclairage & systèmes LV",
    "mep_img_3": "Plomberie & drainage",
    "mep_img_4": "BMS & systèmes de contrôle",
    "decor_img_1": "Plafonds gypsum & cloisons",
    "decor_img_2": "Travaux de peinture",
    "decor_img_3": "Sols & carrelage mural",
    "decor_img_4": "Menuiserie & charpenterie",
    "modal_eyebrow": "Quick Contact",
    "modal_title": "Envoyer une demande",
    "form_name": "Your Name",
    "form_contact": "Email / Phone",
    "form_message": "Message",
    "form_send": "Send Email",
    "values_text": "Nous nous engageons à livrer des projets sûrs, de qualité et durables qui créent une valeur à long terme pour nos clients et la communauté.",
    "projects_text": "Choisissez une catégorie pour voir les détails et visuels.",
    "org_leadership_title": "Leadership et supervision stratégique",
    "org_leadership_text": "Direction globale, stratégie, coordination des parties prenantes et gestion de la performance projet."
},
  "es": {
    "nav_about": "Sobre nosotros",
    "nav_services": "Servicios",
    "nav_projects": "Proyectos",
    "nav_clients": "Clientes",
    "nav_contact": "Contacto",
    "btn_enquiry": "Enviar consulta",
    "hero_eyebrow": "Confort de ingeniería. Excelencia en construcción.",
    "hero_title": "Soluciones integradas de ingeniería confiables",
    "hero_text": "Ofrecemos soluciones HVAC, civiles, MEP y de decoración interior con seguridad, integridad y alto rendimiento.",
    "btn_services": "Nuestros servicios",
    "btn_projects": "Ver proyectos",
    "pill_hvac": "Soluciones HVAC",
    "pill_civil": "Obras civiles",
    "pill_mep": "Servicios MEP",
    "pill_interior": "Decoración interior",
    "hero_card_title": "Socio de ingeniería con base en Qatar",
    "hero_card_text": "Para proyectos residenciales, comerciales e industriales.",
    "project_hvac_label": "HVAC Projects",
    "project_hvac_title": "Central Chilled Water Plant",
    "project_hvac_text": "AHU/FAHU, ducting works, VRF/VRV systems, testing and balancing.",
    "project_civil_label": "Civil Projects",
    "project_civil_title": "Structural & Concrete Works",
    "project_civil_text": "Concrete, block work, masonry, waterproofing and external finishes.",
    "project_mep_label": "MEP Projects",
    "project_mep_title": "Electrical & Plumbing Systems",
    "project_mep_text": "Power distribution, lighting, drainage systems, BMS and control systems.",
    "project_interior_label": "Decoration Projects",
    "project_interior_title": "Fit-Out & Finishing Works",
    "project_interior_text": "Gypsum ceiling, painting, wall tiling, flooring, joinery and carpentry.",
    "about_eyebrow": "Sobre Doha Call Line (DCL)",
    "about_title": "Soluciones de ingeniería que construyen mejores futuros.",
    "about_text_1": "Doha Call Line es una empresa multidisciplinaria en Qatar que ofrece soluciones HVAC, obras civiles, MEP y decoración interior.",
    "about_text_2": "Con más de una década de experiencia, DCL es un socio reconocido por calidad, seguridad y entrega puntual.",
    "stat_years": "Años de experiencia",
    "stat_projects": "Proyectos completados",
    "stat_team": "Profesionales calificados",
    "vision_title": "Visión",
    "vision_text": "Ser un proveedor líder de ingeniería y construcción en Qatar, reconocido por calidad, innovación, confiabilidad y sostenibilidad.",
    "mission_title": "Misión",
    "mission_text": "Entregar soluciones HVAC, civiles, MEP y decoración interior de alta calidad con experiencia, integridad y compromiso.",
    "values_eyebrow": "Valores centrales",
    "values_title": "Entrega segura, de calidad y sostenible.",
    "value_quality": "Calidad",
    "value_quality_text": "Entregamos calidad en todo lo que hacemos.",
    "value_safety": "Seguridad",
    "value_safety_text": "Priorizamos la seguridad de nuestra gente, clientes y proyectos.",
    "value_integrity": "Integridad",
    "value_integrity_text": "Operamos con honestidad, transparencia y justicia.",
    "value_innovation": "Innovación",
    "value_innovation_text": "Adoptamos nuevas ideas y tecnología para mejores soluciones.",
    "value_sustainability": "Sostenibilidad",
    "value_sustainability_text": "Estamos comprometidos con la responsabilidad ambiental.",
    "value_teamwork": "Trabajo en equipo",
    "value_teamwork_text": "Creemos en la colaboración para alcanzar la excelencia.",
    "services_eyebrow": "Descubra nuestros servicios",
    "services_title": "Servicios de ingeniería completos en una sola plataforma.",
    "services_text": "Alcances claros, ejecución coordinada y entrega confiable en HVAC, civil, MEP e interiorismo.",
    "svc_hvac_title": "Soluciones HVAC",
    "svc_hvac_text": "Diseño, suministro, instalación, pruebas y mantenimiento de sistemas de aire acondicionado, ventilación y refrigeración.",
    "svc_civil_title": "Obras civiles",
    "svc_civil_text": "Trabajos estructurales, concreto, mampostería, enlucido, alicatado y servicios civiles relacionados.",
    "svc_mep_title": "Servicios MEP",
    "svc_mep_text": "Servicios mecánicos, eléctricos y de plomería, incluyendo HVAC, sistemas eléctricos, plomería, contra incendios y más.",
    "svc_interior_title": "Decoración interior",
    "svc_interior_text": "Diseño interior, fit-out, cielorrasos, pisos, pintura, particiones, iluminación y decoración interior.",
    "solutions_eyebrow": "Soluciones integradas de ingeniería",
    "solutions_title": "Construimos más que proyectos: construimos confianza.",
    "sol_design": "Design & Engineering",
    "sol_design_text": "Technical drawings, calculations and engineering documentation.",
    "sol_procurement": "Procurement & Supply",
    "sol_procurement_text": "Material sourcing, supplier coordination and project logistics.",
    "sol_construction": "Construction & Installation",
    "sol_construction_text": "Site execution by skilled teams with quality and safety control.",
    "sol_testing": "Testing & Commissioning",
    "sol_testing_text": "Performance verification, inspection and handover readiness.",
    "sol_maintenance": "Operation & Maintenance",
    "sol_maintenance_text": "Reliable after-service support and preventive maintenance.",
    "sol_turnkey": "Turnkey Project Delivery",
    "sol_turnkey_text": "One platform from concept to completion.",
    "iso_quality": "Quality Management",
    "iso_env": "Environmental Management",
    "iso_safety": "Occupational Health & Safety",
    "team_eyebrow": "Equipo y organización",
    "team_title": "Organizados para una entrega eficiente.",
    "team_text": "Nuestra estructura asegura entrega eficiente, comunicación clara y responsabilidad.",
    "org_general": "General Manager",
    "org_engineers": "Engineers",
    "org_engineers_text": "Technical design, calculations, project planning and documentation.",
    "org_pm": "Project Managers",
    "org_pm_text": "Planning, budget, scheduling, client coordination and risk management.",
    "org_supervisors": "Supervisors",
    "org_supervisors_text": "Site supervision, quality monitoring and safe execution of works.",
    "org_technicians": "Technicians",
    "org_technicians_text": "Installation, testing, commissioning, operation and maintenance.",
    "org_support": "Support Functions",
    "org_support_text": "Admin, HR, procurement, QA/QC, finance and HSE support.",
    "hse_badge": "Safety First",
    "hse_title": "Salud, seguridad y calidad",
    "hse_text": "Nos comprometemos con la salud, seguridad y bienestar de nuestra gente, clientes y comunidades.",
    "hse_ppe": "PPE Compliance",
    "hse_ppe_text": "Mandatory PPE, helmets, safety shoes, gloves and goggles.",
    "hse_risk": "Risk Assessment",
    "hse_risk_text": "Hazard identification, risk evaluation and control measures.",
    "hse_toolbox": "Toolbox Talks",
    "hse_toolbox_text": "Daily safety briefing, task planning and worker awareness.",
    "hse_emergency": "Emergency Response",
    "hse_emergency_text": "Emergency procedures, evacuation plans and first aid readiness.",
    "hse_quality": "Quality Inspections",
    "hse_quality_text": "Material inspections, method statements and final testing.",
    "hse_record": "Record & Reporting",
    "hse_record_text": "Inspection records, NCR tracking and corrective actions.",
    "why_eyebrow": "Por qué elegirnos",
    "why_title": "Entrega confiable desde la planificación hasta la puesta en marcha.",
    "why_exp": "25+ Years Experience",
    "why_exp_text": "Extensive experience across HVAC, Civil, MEP and fit-out projects.",
    "why_manpower": "Skilled Technical Manpower",
    "why_manpower_text": "Qualified engineers, supervisors, technicians and skilled workers.",
    "why_qaqc": "Quality Assurance & QA/QC",
    "why_qaqc_text": "Strict compliance with specifications, inspection and standards.",
    "why_time": "On-Time Project Delivery",
    "why_time_text": "Efficient planning, coordination and execution without compromising quality.",
    "why_hse": "HSE & Safety Commitment",
    "why_hse_text": "Risk assessment, toolbox talks and safe working procedures.",
    "why_integrated": "Integrated Engineering Solutions",
    "why_integrated_text": "HVAC, Civil, MEP and Interior services under one coordinated platform.",
    "projects_eyebrow": "Nuestros proyectos",
    "projects_title": "Capacidades de proyecto en cada disciplina.",
    "port_hvac": "HVAC Installation",
    "port_civil": "Civil Construction",
    "port_mep": "MEP Systems",
    "port_interior": "Interior Fit-Out",
    "clients_eyebrow": "Clientes principales",
    "clients_title": "Confiados por organizaciones líderes en Qatar.",
    "client_qatar": "Delivered comprehensive MEP solutions for various museum facilities, ensuring world-class comfort, efficiency, and reliability.",
    "client_redco": "Executed HVAC, plumbing, and MEP works for multiple residential, commercial, and infrastructure projects with high quality and on-time delivery.",
    "client_secc": "Partnered on large-scale infrastructure and building projects, providing complete MEP and civil engineering solutions.",
    "client_aljaber": "Delivered a wide range of MEP services across critical and commercial projects, meeting the highest standards of safety, quality, and performance.",
    "contact_eyebrow": "Contacto",
    "contact_title": "Construyamos el futuro juntos.",
    "contact_text": "¿Tienes un proyecto? Contáctanos y entregaremos la solución de ingeniería adecuada.",
    "address_label": "Address",
    "phone_label": "Mobile",
    "email_label": "Emails",
    "footer_tagline": "Confort de ingeniería. Excelencia en construcción.",

    "overview_hvac_title": "PROYECTO HVAC",
    "overview_hvac_text": "Diseño, suministro, instalación, pruebas y mantenimiento de sistemas de aire acondicionado, ventilación y refrigeración.",
    "overview_civil_title": "PROYECTO CIVIL",
    "overview_civil_text": "Trabajos estructurales, concreto, mampostería, enlucido, alicatado y servicios civiles relacionados.",
    "overview_mep_title": "PROYECTO MEP",
    "overview_mep_text": "Servicios mecánicos, eléctricos y de plomería, incluyendo HVAC, sistemas eléctricos, plomería, contra incendios y más.",
    "overview_interior_title": "PROYECTO DECORACIÓN",
    "overview_interior_text": "Diseño interior, fit-out, cielorrasos, pisos, pintura, particiones, iluminación y decoración interior.",
    "svc_hvac_p1": "Cálculo de cargas y diseño del sistema",
    "svc_hvac_p2": "Sistemas VRF/VRV, agua helada y DX",
    "svc_hvac_p3": "Instalación de AHU, FCU, FAHU y RAHU",
    "svc_hvac_p4": "Ductos, aislamiento y distribución de aire",
    "svc_hvac_p5": "Pruebas, puesta en marcha y mantenimiento",
    "svc_civil_p1": "Trabajos estructurales (RCC, acero y mampostería)",
    "svc_civil_p2": "Concreto y encofrado",
    "svc_civil_p3": "Vías, pavimentos e infraestructura",
    "svc_civil_p4": "Excavación, relleno y compactación",
    "svc_civil_p5": "Acabados y remodelación",
    "svc_mep_p1": "Distribución eléctrica (BT/MT)",
    "svc_mep_p2": "Iluminación, emergencia y exterior",
    "svc_mep_p3": "Plomería y sistemas sanitarios",
    "svc_mep_p4": "Alarma contra incendios, extinción y gas",
    "svc_mep_p5": "BMS, ELV, datos y comunicación",
    "svc_mep_p6": "Pruebas, puesta en marcha y mantenimiento",
    "svc_interior_p1": "Diseño interior y planificación de espacios",
    "svc_interior_p2": "Yeso, particiones y cielorrasos",
    "svc_interior_p3": "Pisos (baldosas, mármol, vinilo, alfombra, etc.)",
    "svc_interior_p4": "Pintura, papel tapiz y acabados de pared",
    "svc_interior_p5": "Carpintería, ebanistería y muebles a medida",
    "svc_interior_p6": "Diseño de iluminación y trabajos decorativos",
    "tab_hvac": "Proyectos HVAC",
    "tab_civil": "Obras civiles",
    "tab_mep": "Proyectos MEP",
    "tab_decoration": "Decoración",
    "project_panel_hvac_title": "Soluciones HVAC para confort eficiente y confiable.",
    "project_panel_hvac_text": "Desde plantas de agua helada hasta sistemas VRF/VRV, AHU/FAHU, ductos, pruebas y mantenimiento.",
    "project_panel_civil_title": "Obras civiles ejecutadas con seguridad y precisión.",
    "project_panel_civil_text": "Estructuras, concreto, bloques, mampostería, impermeabilización, acabados y servicios civiles.",
    "project_panel_mep_title": "Sistemas mecánicos, eléctricos y de plomería integrados.",
    "project_panel_mep_text": "Distribución eléctrica, iluminación, sistemas LV, plomería, drenaje, BMS y control.",
    "project_panel_decoration_title": "Fit-out interior con acabados refinados.",
    "project_panel_decoration_text": "Cielorrasos de yeso, particiones, pintura, pisos, revestimientos, carpintería e iluminación decorativa.",
    "hvac_img_1": "Planta central de agua helada",
    "hvac_img_2": "Instalaciones AHU / FAHU",
    "hvac_img_3": "Trabajos de ductos (GI & Fabric)",
    "hvac_img_4": "Sistemas VRF / VRV",
    "civil_img_1": "Trabajos de concreto",
    "civil_img_2": "Trabajos estructurales",
    "civil_img_3": "Bloques y mampostería",
    "civil_img_4": "Impermeabilización",
    "mep_img_1": "Distribución eléctrica",
    "mep_img_2": "Iluminación y sistemas LV",
    "mep_img_3": "Plomería y drenaje",
    "mep_img_4": "BMS y control",
    "decor_img_1": "Cielorrasos de yeso y particiones",
    "decor_img_2": "Trabajos de pintura",
    "decor_img_3": "Pisos y revestimiento de pared",
    "decor_img_4": "Carpintería y ebanistería",
    "modal_eyebrow": "Quick Contact",
    "modal_title": "Enviar consulta",
    "form_name": "Your Name",
    "form_contact": "Email / Phone",
    "form_message": "Message",
    "form_send": "Send Email",
    "values_text": "Estamos comprometidos a entregar proyectos seguros, de calidad y sostenibles que creen valor a largo plazo para nuestros clientes y la comunidad.",
    "projects_text": "Seleccione una categoría para ver detalles e imágenes.",
    "org_leadership_title": "Liderazgo y supervisión estratégica",
    "org_leadership_text": "Dirección general, estrategia, coordinación de partes interesadas y gestión del desempeño del proyecto."
},
  "ar": {
    "nav_about": "من نحن",
    "nav_services": "الخدمات",
    "nav_projects": "المشاريع",
    "nav_clients": "العملاء",
    "nav_contact": "اتصل بنا",
    "btn_enquiry": "إرسال استفسار",
    "hero_eyebrow": "راحة هندسية. تميز في البناء.",
    "hero_title": "حلول هندسية متكاملة يمكنك الوثوق بها",
    "hero_text": "نقدم حلول التكييف والأعمال المدنية والميكانيكية والكهربائية والسباكة والديكور الداخلي بجودة عالية وسلامة ونزاهة.",
    "btn_services": "خدماتنا",
    "btn_projects": "استعرض المشاريع",
    "pill_hvac": "حلول التكييف",
    "pill_civil": "الأعمال المدنية",
    "pill_mep": "خدمات MEP",
    "pill_interior": "الديكور الداخلي",
    "hero_card_title": "شريك هندسي مقره قطر",
    "hero_card_text": "للمشاريع السكنية والتجارية والصناعية.",
    "project_hvac_label": "مشاريع HVAC",
    "project_hvac_title": "محطة مياه مبردة مركزية",
    "project_hvac_text": "تركيب AHU/FAHU وأعمال الدكت وأنظمة VRF/VRV والاختبار والموازنة.",
    "project_civil_label": "مشاريع الأعمال المدنية",
    "project_civil_title": "الأعمال الإنشائية والخرسانية",
    "project_civil_text": "الخرسانة وأعمال البلوك والبناء والعزل والتشطيبات الخارجية.",
    "project_mep_label": "مشاريع MEP",
    "project_mep_title": "أنظمة الكهرباء والسباكة",
    "project_mep_text": "توزيع الطاقة والإضاءة وأنظمة الصرف وBMS وأنظمة التحكم.",
    "project_interior_label": "مشاريع الديكور",
    "project_interior_title": "أعمال التشطيب والديكور",
    "project_interior_text": "أسقف جبس ودهانات وبلاط حوائط وأرضيات ونجارة.",
    "about_eyebrow": "عن دوحة كول لاين (DCL)",
    "about_title": "حلول هندسية تبني مستقبلاً أفضل.",
    "about_text_1": "دوحة كول لاين شركة متعددة التخصصات في قطر تقدم حلول التكييف والأعمال المدنية وMEP والديكور الداخلي للمشاريع السكنية والتجارية والصناعية.",
    "about_text_2": "بخبرة تتجاوز عشر سنوات، أصبحت DCL شريكاً موثوقاً في الهندسة والإنشاء معروفاً بالجودة والسلامة والتسليم في الوقت المحدد.",
    "stat_years": "سنوات خبرة",
    "stat_projects": "مشاريع منجزة",
    "stat_team": "محترفون مهرة",
    "vision_title": "الرؤية",
    "vision_text": "أن نصبح من أبرز مزودي خدمات الهندسة والإنشاء في قطر، معروفين بالجودة والابتكار والاعتمادية والحلول المستدامة.",
    "mission_title": "الرسالة",
    "mission_text": "تقديم حلول عالية الجودة في التكييف والأعمال المدنية وMEP والديكور الداخلي من خلال الخبرة والنزاهة والالتزام بتجاوز توقعات العملاء.",
    "values_eyebrow": "القيم الأساسية",
    "values_title": "تنفيذ آمن وعالي الجودة ومستدام.",
    "value_quality": "الجودة",
    "value_quality_text": "نقدم جودة عالية في كل ما نقوم به.",
    "value_safety": "السلامة",
    "value_safety_text": "نضع سلامة أفرادنا وعملائنا ومشاريعنا في المقدمة.",
    "value_integrity": "النزاهة",
    "value_integrity_text": "نعمل بصدق وشفافية وعدالة.",
    "value_innovation": "الابتكار",
    "value_innovation_text": "نتبنى الأفكار والتقنيات الجديدة لتقديم حلول أفضل.",
    "value_sustainability": "الاستدامة",
    "value_sustainability_text": "نلتزم بالمسؤولية البيئية ومستقبل مستدام.",
    "value_teamwork": "العمل الجماعي",
    "value_teamwork_text": "نؤمن بالتعاون لتحقيق التميز.",
    "services_eyebrow": "اكتشف خدماتنا",
    "services_title": "خدمات هندسية متكاملة في منصة واحدة.",
    "services_text": "نطاقات عمل واضحة وتنفيذ منسق وتسليم موثوق عبر التكييف والأعمال المدنية وخدمات MEP والديكور الداخلي.",
    "svc_hvac_title": "حلول التكييف",
    "svc_hvac_text": "تصميم وتوريد وتركيب واختبار وصيانة أنظمة التكييف والتهوية والتبريد.",
    "svc_civil_title": "الأعمال المدنية",
    "svc_civil_text": "الأعمال الإنشائية والخرسانة والبناء واللياسة والبلاط وجميع خدمات البناء المدني ذات الصلة.",
    "svc_mep_title": "خدمات MEP",
    "svc_mep_text": "الخدمات الميكانيكية والكهربائية والسباكة بما في ذلك HVAC والأنظمة الكهربائية والسباكة ومكافحة الحريق والمزيد.",
    "svc_interior_title": "الديكور الداخلي",
    "svc_interior_text": "التصميم الداخلي والتشطيبات والأسقف والأرضيات والدهانات والقواطع والإضاءة وأعمال الديكور الداخلي.",
    "solutions_eyebrow": "حلول هندسية متكاملة",
    "solutions_title": "نحن لا نبني المشاريع فقط، بل نبني الثقة.",
    "sol_design": "التصميم والهندسة",
    "sol_design_text": "رسومات فنية وحسابات ووثائق هندسية.",
    "sol_procurement": "المشتريات والتوريد",
    "sol_procurement_text": "توريد المواد وتنسيق الموردين والخدمات اللوجستية للمشروع.",
    "sol_construction": "البناء والتركيب",
    "sol_construction_text": "تنفيذ موقعي بواسطة فرق مؤهلة مع ضبط الجودة والسلامة.",
    "sol_testing": "الاختبار والتشغيل",
    "sol_testing_text": "التحقق من الأداء والفحص وجاهزية التسليم.",
    "sol_maintenance": "التشغيل والصيانة",
    "sol_maintenance_text": "دعم ما بعد الخدمة وصيانة وقائية موثوقة.",
    "sol_turnkey": "تسليم مشروع متكامل",
    "sol_turnkey_text": "منصة واحدة من الفكرة إلى الإنجاز.",
    "iso_quality": "إدارة الجودة",
    "iso_env": "الإدارة البيئية",
    "iso_safety": "الصحة والسلامة المهنية",
    "team_eyebrow": "الفريق والتنظيم",
    "team_title": "منظمون لتسليم المشاريع بكفاءة.",
    "team_text": "تم تصميم هيكلنا التنظيمي لضمان التسليم الفعال والتواصل الواضح والمسؤولية.",
    "org_general": "المدير العام",
    "org_engineers": "المهندسون",
    "org_engineers_text": "التصميم الفني والحسابات وتخطيط المشروع والوثائق.",
    "org_pm": "مديرو المشاريع",
    "org_pm_text": "التخطيط والميزانية والجدولة وتنسيق العميل وإدارة المخاطر.",
    "org_supervisors": "المشرفون",
    "org_supervisors_text": "الإشراف الموقعي ومتابعة الجودة والتنفيذ الآمن للأعمال.",
    "org_technicians": "الفنيون",
    "org_technicians_text": "التركيب والاختبار والتشغيل والصيانة.",
    "org_support": "وظائف الدعم",
    "org_support_text": "الإدارة والموارد البشرية والمشتريات وQA/QC والمالية ودعم HSE.",
    "hse_badge": "السلامة أولاً",
    "hse_title": "الصحة والسلامة والجودة",
    "hse_text": "نلتزم بصحة وسلامة ورفاهية موظفينا وعملائنا والمجتمعات التي نعمل فيها.",
    "hse_ppe": "الالتزام بمعدات الوقاية",
    "hse_ppe_text": "الالتزام بمعدات الوقاية والخوذ وأحذية السلامة والقفازات والنظارات.",
    "hse_risk": "تقييم المخاطر",
    "hse_risk_text": "تحديد المخاطر وتقييمها ووضع إجراءات التحكم.",
    "hse_toolbox": "اجتماعات السلامة",
    "hse_toolbox_text": "توعية يومية بالسلامة وتخطيط المهام ورفع وعي العمال.",
    "hse_emergency": "الاستجابة للطوارئ",
    "hse_emergency_text": "إجراءات الطوارئ وخطط الإخلاء وجاهزية الإسعافات الأولية.",
    "hse_quality": "فحوصات الجودة",
    "hse_quality_text": "فحص المواد واعتماد طرق العمل والاختبار النهائي.",
    "hse_record": "السجلات والتقارير",
    "hse_record_text": "سجلات الفحص ومتابعة NCR والإجراءات التصحيحية.",
    "why_eyebrow": "لماذا تختارنا",
    "why_title": "تسليم موثوق من التخطيط إلى التشغيل.",
    "why_exp": "خبرة أكثر من 10 سنوات",
    "why_exp_text": "خبرة واسعة في مشاريع HVAC والأعمال المدنية وMEP والتشطيبات.",
    "why_manpower": "كوادر فنية مؤهلة",
    "why_manpower_text": "مهندسون ومشرفون وفنيون وعمال مهرة مؤهلون.",
    "why_qaqc": "ضمان الجودة وQA/QC",
    "why_qaqc_text": "التزام صارم بالمواصفات والفحص والمعايير.",
    "why_time": "تسليم المشاريع في الوقت المحدد",
    "why_time_text": "تخطيط وتنسيق وتنفيذ فعال دون التأثير على الجودة.",
    "why_hse": "الالتزام بالصحة والسلامة",
    "why_hse_text": "تقييم المخاطر واجتماعات السلامة وإجراءات العمل الآمنة.",
    "why_integrated": "حلول هندسية متكاملة",
    "why_integrated_text": "خدمات HVAC والأعمال المدنية وMEP والديكور ضمن منصة واحدة منسقة.",
    "projects_eyebrow": "مشاريعنا",
    "projects_title": "قدرات تنفيذ المشاريع في جميع التخصصات.",
    "port_hvac": "تركيب HVAC",
    "port_civil": "الإنشاءات المدنية",
    "port_mep": "أنظمة MEP",
    "port_interior": "التشطيبات الداخلية",
    "clients_eyebrow": "العملاء الرئيسيون",
    "clients_title": "موثوقون من قبل مؤسسات رائدة في قطر.",
    "client_qatar": "قدمنا حلول MEP متكاملة لمرافق المتاحف لضمان الراحة والكفاءة والموثوقية.",
    "client_redco": "نفذنا أعمال HVAC والسباكة وMEP لمشاريع سكنية وتجارية وبنية تحتية متعددة بجودة عالية وتسليم في الوقت.",
    "client_secc": "تعاونّا في مشاريع بنية تحتية ومبانٍ واسعة النطاق مع حلول MEP وأعمال مدنية متكاملة.",
    "client_aljaber": "قدمنا مجموعة واسعة من خدمات MEP للمشاريع الحرجة والتجارية وفق أعلى معايير السلامة والجودة والأداء.",
    "contact_eyebrow": "اتصل بنا",
    "contact_title": "لنبني المستقبل معاً.",
    "contact_text": "هل لديك مشروع؟ تواصل معنا وسنقدم الحل الهندسي المناسب.",
    "address_label": "العنوان",
    "phone_label": "الجوال",
    "email_label": "البريد الإلكتروني",
    "footer_tagline": "راحة هندسية. تميز في البناء.",

    "overview_hvac_title": "مشاريع HVAC",
    "overview_hvac_text": "تصميم وتوريد وتركيب واختبار وصيانة أنظمة التكييف والتهوية والتبريد.",
    "overview_civil_title": "مشاريع الأعمال المدنية",
    "overview_civil_text": "الأعمال الإنشائية والخرسانة والبناء واللياسة والبلاط وجميع خدمات البناء المدني ذات الصلة.",
    "overview_mep_title": "مشاريع MEP",
    "overview_mep_text": "الخدمات الميكانيكية والكهربائية والسباكة بما في ذلك HVAC والأنظمة الكهربائية والسباكة ومكافحة الحريق والمزيد.",
    "overview_interior_title": "مشاريع الديكور",
    "overview_interior_text": "التصميم الداخلي والتشطيبات والأسقف والأرضيات والدهانات والقواطع والإضاءة وأعمال الديكور الداخلي.",
    "svc_hvac_p1": "حساب الأحمال وتصميم الأنظمة",
    "svc_hvac_p2": "أنظمة VRF/VRV والمياه المبردة وDX",
    "svc_hvac_p3": "تركيب AHU وFCU وFAHU وRAHU",
    "svc_hvac_p4": "الدكت والعزل وتوزيع الهواء",
    "svc_hvac_p5": "الاختبار والتشغيل والصيانة",
    "svc_civil_p1": "الأعمال الإنشائية (خرسانة مسلحة، فولاذ وبناء)",
    "svc_civil_p2": "أعمال الخرسانة والشدات",
    "svc_civil_p3": "الطرق والرصف والبنية التحتية",
    "svc_civil_p4": "الحفر والردم والدمك",
    "svc_civil_p5": "أعمال التشطيب والتجديد",
    "svc_mep_p1": "توزيع الطاقة الكهربائية (LV/MV)",
    "svc_mep_p2": "الإضاءة والطوارئ والإضاءة الخارجية",
    "svc_mep_p3": "السباكة والأنظمة الصحية",
    "svc_mep_p4": "إنذار الحريق ومكافحة الحريق وأنظمة الغاز",
    "svc_mep_p5": "BMS وELV والبيانات والاتصالات",
    "svc_mep_p6": "الاختبار والتشغيل والصيانة",
    "svc_interior_p1": "التصميم الداخلي وتخطيط المساحات",
    "svc_interior_p2": "أعمال الجبس والقواطع والأسقف",
    "svc_interior_p3": "الأرضيات (بلاط، رخام، فينيل، سجاد وغيرها)",
    "svc_interior_p4": "الدهانات وورق الجدران وتشطيبات الحوائط",
    "svc_interior_p5": "النجارة والأثاث المخصص",
    "svc_interior_p6": "تصميم الإضاءة والأعمال الديكورية",
    "tab_hvac": "مشاريع HVAC",
    "tab_civil": "الأعمال المدنية",
    "tab_mep": "مشاريع MEP",
    "tab_decoration": "مشاريع الديكور",
    "project_panel_hvac_title": "حلول HVAC لكفاءة وراحة موثوقة في المباني.",
    "project_panel_hvac_text": "من محطات المياه المبردة إلى أنظمة VRF/VRV وتركيب AHU/FAHU والدكت والاختبار والصيانة.",
    "project_panel_civil_title": "أعمال مدنية تُنفذ بأمان ودقة.",
    "project_panel_civil_text": "أعمال إنشائية وخرسانية وبلوك وبناء وعزل وتشطيبات وخدمات مدنية ذات صلة.",
    "project_panel_mep_title": "أنظمة ميكانيكية وكهربائية وسباكة متكاملة.",
    "project_panel_mep_text": "توزيع كهرباء وإضاءة وأنظمة LV وسباكة وصرف وBMS وأنظمة تحكم.",
    "project_panel_decoration_title": "تشطيبات داخلية وديكور بجودة عالية.",
    "project_panel_decoration_text": "أسقف جبس وقواطع ودهانات وأرضيات وبلاط حوائط ونجارة وإضاءة ديكورية.",
    "hvac_img_1": "محطة مياه مبردة مركزية",
    "hvac_img_2": "تركيب AHU / FAHU",
    "hvac_img_3": "أعمال الدكت (GI و Fabric)",
    "hvac_img_4": "أنظمة VRF / VRV",
    "civil_img_1": "أعمال الخرسانة",
    "civil_img_2": "الأعمال الإنشائية",
    "civil_img_3": "أعمال البلوك والبناء",
    "civil_img_4": "أعمال العزل المائي",
    "mep_img_1": "توزيع الطاقة الكهربائية",
    "mep_img_2": "الإضاءة وأنظمة LV",
    "mep_img_3": "أنظمة السباكة والصرف",
    "mep_img_4": "BMS وأنظمة التحكم",
    "decor_img_1": "أسقف جبس وقواطع",
    "decor_img_2": "أعمال الدهانات",
    "decor_img_3": "الأرضيات وبلاط الحوائط",
    "decor_img_4": "النجارة والأعمال الخشبية",
    "modal_eyebrow": "تواصل سريع",
    "modal_title": "إرسال استفسار",
    "form_name": "الاسم",
    "form_contact": "البريد / الهاتف",
    "form_message": "الرسالة",
    "form_send": "إرسال البريد",
    "values_text": "نحن ملتزمون بتنفيذ مشاريع آمنة وعالية الجودة ومستدامة تخلق قيمة طويلة الأمد لعملائنا والمجتمع.",
    "projects_text": "اختر فئة المشروع لعرض التفاصيل والصور.",
    "org_leadership_title": "القيادة والإشراف الاستراتيجي",
    "org_leadership_text": "التوجيه العام والاستراتيجية وتنسيق أصحاب المصلحة وإدارة أداء المشاريع."
}
};

const navToggle = document.querySelector('.nav-toggle');
const navLinks = document.getElementById('navLinks');
const themeToggle = document.getElementById('themeToggle');
const languageSelect = document.getElementById('languageSelect');
const modal = document.getElementById('enquiryModal');
const openButtons = document.querySelectorAll('.open-enquiry');
const closeButtons = document.querySelectorAll('[data-close-modal]');
const enquiryForm = document.getElementById('enquiryForm');

function setLanguage(lang) {
  if (!['en', 'ar'].includes(lang)) lang = 'en';
  const dict = translations[lang] || translations.en;
  const fallback = translations.en;
  document.documentElement.lang = lang;
  document.documentElement.dir = 'ltr';
  document.body.setAttribute('data-lang', lang);
  document.body.classList.toggle('lang-ar', lang === 'ar');
  document.querySelectorAll('[data-i18n]').forEach(el => {
    const key = el.getAttribute('data-i18n');
    const value = dict[key] || fallback[key] || '';
    if (value) el.textContent = value;
  });
  localStorage.setItem('dcl_lang', lang);
}

function setTheme(theme) {
  document.body.classList.toggle('dark', theme === 'dark');
  localStorage.setItem('dcl_theme', theme);
}

if (navToggle && navLinks) {
  navToggle.addEventListener('click', () => {
    const open = navLinks.classList.toggle('active');
    navToggle.setAttribute('aria-expanded', String(open));
  });
  navLinks.querySelectorAll('a').forEach(link => link.addEventListener('click', () => {
    navLinks.classList.remove('active');
    navToggle.setAttribute('aria-expanded', 'false');
  }));
}

if (themeToggle) {
  themeToggle.addEventListener('click', () => {
    setTheme(document.body.classList.contains('dark') ? 'light' : 'dark');
  });
}

if (languageSelect) {
  languageSelect.addEventListener('change', (e) => setLanguage(e.target.value));
}

function openModal() {
  modal.classList.add('active');
  modal.setAttribute('aria-hidden', 'false');
  document.body.style.overflow = 'hidden';
}
function closeModal() {
  modal.classList.remove('active');
  modal.setAttribute('aria-hidden', 'true');
  document.body.style.overflow = '';
}
openButtons.forEach(button => button.addEventListener('click', openModal));
closeButtons.forEach(button => button.addEventListener('click', closeModal));
document.addEventListener('keydown', e => {
  if (e.key === 'Escape' && modal.classList.contains('active')) closeModal();
});

if (enquiryForm) {
  enquiryForm.addEventListener('submit', event => {
    event.preventDefault();
    const data = new FormData(enquiryForm);
    const name = encodeURIComponent(data.get('name'));
    const contact = encodeURIComponent(data.get('contact'));
    const message = encodeURIComponent(data.get('message'));
    const subject = encodeURIComponent('Website Enquiry - Doha Call Line');
    const body = `Name:%20${name}%0AEmail%20/%20Phone:%20${contact}%0A%0AMessage:%0A${message}`;
    window.location.href = `mailto:info@dohacallline.com?subject=${subject}&body=${body}`;
  });
}

// Hero slider
const heroSlides = document.querySelectorAll('.hero-bg');
let slideIndex = 0;
setInterval(() => {
  if (!heroSlides.length) return;
  heroSlides[slideIndex].classList.remove('active');
  slideIndex = (slideIndex + 1) % heroSlides.length;
  heroSlides[slideIndex].classList.add('active');
}, 4800);

// Smooth reveal animation
const revealObserver = new IntersectionObserver(entries => {
  entries.forEach(entry => {
    if (entry.isIntersecting) {
      entry.target.classList.add('visible');
      revealObserver.unobserve(entry.target);
    }
  });
}, { threshold: 0.12, rootMargin: '0px 0px -40px 0px' });

document.querySelectorAll('.reveal').forEach(el => revealObserver.observe(el));

// Project category accordion
const projectTabs = document.querySelectorAll('.project-tab');
const projectPanels = document.querySelectorAll('.project-panel');
projectTabs.forEach(tab => {
  tab.addEventListener('click', () => {
    const key = tab.getAttribute('data-project');
    const panel = document.getElementById(`panel-${key}`);
    const alreadyActive = tab.classList.contains('active') && panel && panel.classList.contains('active');

    projectTabs.forEach(item => item.classList.remove('active'));
    projectPanels.forEach(item => item.classList.remove('active'));

    if (!alreadyActive && panel) {
      tab.classList.add('active');
      panel.classList.add('active');
    }
  });
});

// Initial settings
const savedTheme = localStorage.getItem('dcl_theme');
const preferredTheme = window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light';
const savedLang = ['en','ar'].includes(localStorage.getItem('dcl_lang')) ? localStorage.getItem('dcl_lang') : 'en';
setTheme(savedTheme || preferredTheme);
if (!savedTheme && window.matchMedia) {
  window.matchMedia('(prefers-color-scheme: dark)').addEventListener('change', event => {
    if (!localStorage.getItem('dcl_theme')) setTheme(event.matches ? 'dark' : 'light');
  });
}
if (languageSelect) languageSelect.value = savedLang;
setLanguage(savedLang);


// Major Clients image sliders: 3 images per company, clean automatic fade + clickable dots
const clientCards = document.querySelectorAll('.client-showcase');
clientCards.forEach((card, cardIndex) => {
  const slides = card.querySelectorAll('.client-slide');
  const dots = card.querySelectorAll('.client-dot');
  let index = 0;
  let timer;

  function showClientSlide(nextIndex) {
    index = nextIndex;
    slides.forEach((slide, i) => slide.classList.toggle('active', i === index));
    dots.forEach((dot, i) => dot.classList.toggle('active', i === index));
  }

  function startSlider() {
    timer = setInterval(() => {
      showClientSlide((index + 1) % slides.length);
    }, 3200 + (cardIndex * 180));
  }

  dots.forEach((dot, i) => {
    dot.addEventListener('click', () => {
      clearInterval(timer);
      showClientSlide(i);
      startSlider();
    });
  });

  startSlider();
});
